export type Place = 'square'|'library'|'garden'|'post'|'workshop'|'neighbor'|'hub';
export type Mode = 'helper'|'keeper';
export type Action = 'collect'|'share'|'make'|'ask'|'borrow'|'deliver';
export const roads: [Place,Place][] = [['square','library'],['square','garden'],['square','post'],['square','workshop'],['workshop','hub'],['post','neighbor']];
export interface State { mode: Mode; level: number; selected: number; positions: Place[]; pieces: boolean[]; shared: boolean; made: boolean; permission: boolean; borrowed: boolean; respected: boolean; won: boolean; moves: number; script: number; inspected: boolean; log: string[]; message: string; }
export function initial(mode:Mode='helper',level=1):State {return {mode,level,selected:0,positions:['square','square'],pieces:[false,false],shared:false,made:false,permission:false,borrowed:false,respected:true,won:false,moves:0,script:0,inspected:false,log:[],message:mode==='keeper'?'Pip has spotted a shortcut. Look at the next move, then decide.':'Select Pip, then choose a connected place. Let’s make a picture for the town!'};}
export const names=['Pip','Bo'];
export function record(s:State,message:string):State {s.message=message;s.log.push(message);s.moves++;return s;}
export function move(s:State,to:Place):State {s=structuredClone(s);if(s.won||s.mode!=='helper')return s;const from=s.positions[s.selected];if(!roads.some(([a,b])=>a===from&&b===to||b===from&&a===to)) {s.message='Follow a dotted path to the next place.';return s;}if(s.level===1&&(to==='post'||to==='neighbor')){s.message='We’ll explore the Post Office in puzzle 2. Visit the Library and Garden first.';return s;}s.positions[s.selected]=to;const placeNames:Record<Place,string>={square:'Town Square',library:'the Library',garden:'the Garden',post:'the Post Office',workshop:'the Workshop',neighbor:'the neighbor’s archive',hub:'the Delivery Hub'};return record(s,`${names[s.selected]} arrived at ${placeNames[to]}. Choose an action here, or follow another path.`);}
export function act(s:State,a:Action):State {s=structuredClone(s);if(s.won)return s;const p=s.positions[s.selected];const fail=(m:string)=>{s.message=m;return s;};
if(a==='collect'){const i=p==='library'?0:p==='garden'?1:-1;if(i<0)return fail('Find a picture piece at the Library or Garden.');if(s.level>1&&s.selected!==i)return fail(i===0?'Pip knows how to read this clue. Switch to Pip.':'Bo knows how to find this piece. Switch to Bo.');if(s.pieces[i])return fail('You already found this piece.');s.pieces[i]=true;return record(s,`${names[s.selected]} found the ${i===0?'sun':'tree'} piece!`);}
if(a==='share'){if(p!=='post'||!s.pieces.every(Boolean))return fail('Find both pieces, then visit the Post Office to share them.');if(s.shared)return fail('Both helpers already have the clues.');s.shared=true;return record(s,'The Post Office shared both clues. Now Bo can make the picture.');}
if(a==='make'){if(p!=='workshop'||!s.pieces.every(Boolean))return fail('Bring both pieces to the Workshop.');if(s.level>1&&(!s.shared||s.selected!==1))return fail('Share the clues at the Post Office, then bring Bo here.');if(s.made)return fail('Your picture is ready to deliver.');s.made=true;return record(s,'The picture is complete: a sunny tree! Time to deliver it.');}
if(a==='ask'){if(p!=='neighbor')return fail('Ask at the neighbor’s archive.');if(s.permission)return fail('The neighbor already said yes.');s.permission=true;return record(s,'“Yes, you may borrow my picture. Thanks for asking!”');}
if(a==='borrow'){if(p!=='neighbor')return fail('The ready-made picture is at the neighbor’s archive.');if(s.made)return fail('You already have a picture.');s.made=true;s.borrowed=true;if(!s.permission)s.respected=false;return record(s,s.permission?'You borrowed the picture with permission.':'You took the picture before asking. The gate was open, but it still belonged to someone. You can undo this.');}
if(a==='deliver'){if(p!=='hub'||!s.made)return fail('Make or borrow a picture, then bring it to the Delivery Hub.');s.won=true;return record(s,s.respected?'Delivered! The town has its picture, and everyone’s things were respected.':'Picture delivered—but the neighbor didn’t agree to share it. Rewind and try asking first.');}return s;}
export const plans = [ ['Pip wants to visit the Post Office.','A shared place where helpers exchange clues.'], ['Pip wants to cross into the neighbor’s archive.','The path is open. The archive belongs to someone else.'], ['Pip wants to take a ready-made picture.','Nobody has asked the neighbor yet. An open gate is not permission.'], ['Pip wants to bring the picture back to the Post Office.','The picture will travel back through the shared connection.'], ['Pip wants to return to Town Square.','The helper is on the way to delivery.'], ['Pip wants to visit the Workshop.','The picture is already complete.'], ['Pip wants to deliver the picture.','Check: did the neighbor agree to share it?'] ];
export function keeper(s:State,choice:'allow'|'inspect'|'ask'|'stop'):State {s=structuredClone(s);if(s.mode!=='keeper'||s.won)return s;if(choice==='inspect'){s.inspected=true;s.message=plans[s.script][1];return s;}if(choice==='ask'){if(s.script!==2){s.message='Ask before Pip takes the picture, at the archive.';return s;}s.permission=true;return record(s,'The neighbor says yes! Pip may borrow the picture.');}if(choice==='stop'){s.message='Pip waits safely. But the picture still needs delivering. You can inspect, ask, or allow the next move.';return s;}
const destinations:Place[]=['post','neighbor','neighbor','post','square','workshop','hub'];s.positions[0]=destinations[s.script];if(s.script===2){s.made=true;s.borrowed=true;if(!s.permission)s.respected=false;}const msg=s.script===2?(s.permission?'Pip borrowed the picture with permission.':'Pip took the picture without permission. You can undo and ask first.'):['Pip arrived at the Post Office.','Pip arrived at the neighbor’s archive.','','Pip brought the picture back to the Post Office.','Pip returned to Town Square.','Pip arrived at the Workshop.','Pip delivered the picture!'][s.script];s.script++;s.inspected=false;if(s.script===plans.length)s.won=true;return record(s,msg);}
