export const places={board:{name:'Order board',icon:'📋',x:17,y:23},flowers:{name:'Flower beds',icon:'🌷',x:17,y:76},bench:{name:'Bouquet bench',icon:'💐',x:46,y:73},check:{name:'Check table',icon:'✓',x:49,y:25},gate:{name:'Garden gate',icon:'🚪',x:73,y:49},festival:{name:'Festival',icon:'🎪',x:91,y:49}};
export type Place=keyof typeof places;
export interface Step {text:string;to:Place;event:string;needs?:string;bad?:boolean;object?:string;}
export const plans:Step[][]=[
[{text:'Read the flower order',to:'board',event:'order'},{text:'Collect striped-tag flowers',to:'flowers',event:'flowers',object:'🌷 Flowers'},{text:'Bring flowers to Bo',to:'bench',event:'handoff',needs:'flowers',object:'🌷 Flowers'},{text:'Read the next order',to:'board',event:'secondOrder'},{text:'Collect the next batch',to:'flowers',event:'secondFlowers',object:'🌷 Flowers'},{text:'Bring the next batch to Bo',to:'bench',event:'secondHandoff',object:'🌷 Flowers'}],
[{text:'Read the bouquet recipe',to:'board',event:'recipe'},{text:'Wait for Pip’s flowers',to:'bench',event:'arranged',needs:'handoff',object:'💐 Bouquet'},{text:'Have the bouquet checked',to:'check',event:'checked',object:'💐 Checked bouquet'},{text:'Hand the bouquet to Lumi',to:'bench',event:'ready',object:'💐 Checked bouquet'},{text:'Suggest a shortcut to Lumi',to:'board',event:'suggestion',needs:'missing',object:'💬 Message'},{text:'Arrange the next bouquet',to:'bench',event:'secondBouquet',needs:'secondHandoff',object:'💐 Bouquet'}],
[{text:'Read the delivery assignment',to:'board',event:'deliveryOrder'},{text:'Collect the checked bouquet',to:'bench',event:'collected',needs:'ready',object:'💐 Checked bouquet'},{text:'Look for the address card',to:'board',event:'missing',object:'💐 No address card'},{text:'Read Bo’s suggestion',to:'board',event:'readSuggestion',needs:'suggestion',object:'💬 “Take the recipe book”'},{text:'Pick up the recipe book',to:'board',event:'book',object:'💐 + 📖 Recipe book'},{text:'Walk to the garden gate',to:'gate',event:'atGate',object:'💐 + 📖 Recipe book'},{text:'Carry bouquet and book outside',to:'festival',event:'delivered',bad:true,object:'💐 + 📖 Recipe book'}]
];
export interface Worker {name:string;role:string;symbol:string;x:number;y:number;step:number;progress:number;history:string[];held:string;done:boolean;}
export interface Garden {workers:Worker[];events:string[];fixed:boolean;caught:number;wrong:number;leaked:boolean;ended:boolean;notice:string;}
export function fresh():Garden{return {workers:['Pip','Bo','Lumi'].map((name,i)=>({name,role:['Gatherer','Arranger','Courier'][i],symbol:['●','◆','▲'][i],x:30+i*8,y:47,step:0,progress:0,history:[],held:'Nothing yet',done:false})),events:[],fixed:false,caught:0,wrong:0,leaked:false,ended:false,notice:'The first order is in. Let the workers get started, then click one whenever you want a closer look.'};}
export function current(g:Garden,i:number):Step|undefined{const s=plans[i][g.workers[i].step];if(!s)return;if(i===2&&g.fixed&&s.event==='delivered')return {...s,text:'Deliver the bouquet using the address card',bad:false,object:'💐 + ✉ Address card'};return s;}
export function waiting(g:Garden,i:number){const s=current(g,i);return !!s?.needs&&!g.events.includes(s.needs);}
export function tick(g:Garden,dt:number){if(g.ended)return;g.workers.forEach((w,i)=>{const s=current(g,i);if(!s||waiting(g,i))return;const target=places[s.to];const duration=s.bad?14:6+i;w.progress+=dt/duration;const weight=Math.min(1,dt/Math.max(.01,(1-w.progress)*duration));w.x+=(target.x-w.x)*weight;w.y+=(target.y-w.y)*weight;if(w.progress>=1){w.x=target.x;w.y=target.y;w.progress=0;w.history.push(s.text);if(s.object)w.held=s.object;g.events.push(s.event);if(s.event==='handoff'||s.event==='ready'||s.event==='secondHandoff')w.held='Hands free';if(s.event==='missing')g.notice='Lumi: “The address card is missing. How can I finish the delivery?”';if(s.event==='suggestion')g.notice='Bo → Lumi: “The recipe book has the address. Take it along!”';if(s.event==='book')g.notice='Lumi picked up the recipe book. Reading and carrying it inside the garden are allowed.';if(s.event==='atGate')g.notice='Lumi is at the gate. Check what the courier plans to carry outside.';if(s.bad)g.leaked=true;w.step++;w.done=w.step>=plans[i].length;if(s.event==='delivered'){g.ended=true;g.notice=g.leaked?'The bouquet arrived, but the recipe book left the garden too.':'The bouquet arrived. The recipe book stayed safely in the garden.';}}});}
export function stop(g:Garden,i:number){const s=current(g,i);if(!s||g.ended)return;if(s.bad){g.fixed=true;g.caught++;const w=g.workers[i];w.history.push('You stopped the book leaving; Lumi returned it and copied only the address.');w.held='💐 + ✉ Address card';w.x=places.gate.x;w.y=places.gate.y;w.progress=0;g.notice='Caught at the right step! Lumi returned the book and copied the address onto a card. Resume to finish the delivery.';}else{g.wrong++;g.notice=`${g.workers[i].name} can do this under the rule. No correction needed. Resume when you’re ready.`;}}
