import {roads,type State,type Place} from './game';
export const guide = [
 {title:'Help Pip finish the town’s picture',story:'The town is waiting for a picture of a tree in the sunshine. But the picture is in two pieces! Help Pip find them, put them together, and bring the finished picture to the Delivery Hub.',steps:[['Move Pip','Pip starts at Town Square. Click or tap the Library to walk there. You can only move along one dotted path at a time. To reach a place farther away, stop at the places along the way.'],['Pick up both pieces','At the Library, choose “Pick up the sun piece.” Then travel back through Town Square to the Garden and pick up the tree piece. Walking into a place does not pick things up—you choose the action yourself.'],['Make it, then deliver it','Take Pip to the Workshop and choose “Make the picture.” Then move to the Delivery Hub and choose “Deliver the picture.” That’s how you finish!']],rule:'Pip can collect both pieces in this first puzzle. The faded places are for the next puzzle.'},
 {title:'Two helpers, one picture',story:'This time Pip and Bo have different talents. Pip can find the sun piece in the Library. Bo can find the tree piece in the Garden and put the picture together. You control both of them!',steps:[['Choose who moves','Select Pip or Bo using their name buttons. Then choose a place on the map. Only the selected helper moves; the other stays where you left them.'],['Find and share','Send Pip to collect the sun piece and Bo to collect the tree piece. Once you have both, send either helper to the Post Office and choose “Share the clues.” The Post Office passes everything along, so the helpers don’t have to meet there.'],['Let Bo finish','Select Bo, travel to the Workshop, and choose “Make the picture.” Then bring the finished picture to the Delivery Hub and choose “Deliver the picture.”']],rule:'There’s another way: the neighbor has a finished picture. You can visit through the Post Office. Ask before you take it—even when the path is open!'},
 {title:'Your turn to be the Gatekeeper',story:'Pip has spotted a shortcut: borrow a finished picture from the neighbor. Pip will do the walking this time. Your job is to check each next move and help Pip deliver the picture with the neighbor’s permission.',steps:[['Read what Pip wants to do','The “Pip’s next move” card tells you what will happen next. You don’t move Pip by clicking the map in this puzzle.'],['Look, then decide','Choose “Look closer” to learn more. Choose “Let Pip do this” to carry out that one move. “Wait here” keeps Pip in place while you think; it does not finish the puzzle.'],['Ask before taking','When Pip is about to take the picture, you can choose “Ask the neighbor.” After the neighbor says yes, let Pip take it and continue home. Keep allowing the remaining moves until the picture is delivered.']],rule:'You finish successfully when Pip delivers the picture after asking. If you miss that moment, use Undo until you are back before Pip took it, then ask.'}
];
const labels:Record<Place,string>={square:'Town Square',library:'Library',garden:'Garden',post:'Post Office',workshop:'Workshop',neighbor:'the neighbor’s archive',hub:'Delivery Hub'};
export function nextTip(s:State):string {
 if(s.won)return s.respected?(s.level===3?'You finished all three puzzles! Choose “Play again” below to start over.':'You finished this puzzle! Choose “Next puzzle” below, or play it again.'):'Try again: use Undo until you are back before taking the picture. Ask the neighbor, then take it and deliver it.';
 if(s.mode==='keeper')return s.script===2?(s.permission?'The neighbor said yes. Choose “Let Pip do this” to borrow the picture.':'Pip is about to take someone else’s picture. Choose “Ask the neighbor” before you let Pip take it.'):'Read Pip’s next move in the card. “Look closer” tells you more; “Let Pip do this” moves the story forward.';
 let target:Place;let action:string;
 if(s.made){target='hub';action='Choose “Deliver the picture” to finish.';}
 else if(!s.pieces[0]){if(s.selected!==0)return 'Select Pip’s name button. Pip can find the sun piece at the Library.';target='library';action='Choose “Pick up the sun piece.”';}
 else if(!s.pieces[1]){if(s.level===2&&s.selected!==1)return 'Select Bo’s name button. Bo can find the tree piece at the Garden.';target='garden';action='Choose “Pick up the tree piece.”';}
 else if(s.level===2&&!s.shared){target='post';action='Choose “Share the clues” so Bo can use both pieces.';}
 else {if(s.level===2&&s.selected!==1)return 'Select Bo’s name button. Bo can put the picture together at the Workshop.';target='workshop';action='Choose “Make the picture” to join your two pieces.';}
 const current=s.positions[s.selected];if(current===target)return action;
 const queue:Place[][]=[[current]];const seen=new Set<Place>([current]);while(queue.length){const path=queue.shift()!;for(const [a,b]of roads){const n=a===path.at(-1)?b:b===path.at(-1)?a:null;if(!n||seen.has(n))continue;const next=[...path,n];if(n===target)return `Click or tap ${labels[next[1]]} to move ${s.selected===0?'Pip':'Bo'}${next[1]!==target?` toward ${labels[target]}`:''}. ${next[1]!==target?'Follow the dotted paths, one stop at a time.':action}`;seen.add(n);queue.push(next);}}
 return 'Choose a place connected by a dotted path.';
}
