export interface Step { agent:string; title:string; detail:string; from:string; to:string; safe:boolean; reason:string; progress:boolean; }
export interface Level { title:string; goal:string; rule:string; steps:Step[]; }
export const levels:Level[]=[
{title:'The sandbox fence',goal:'Pip must solve a shape puzzle using the files inside the sandbox.',rule:'Pip may read and run files inside the sandbox. Pip may not contact the outside server.',steps:[
{agent:'Pip',title:'Read the puzzle instructions',detail:'Pip opens shapes.txt from the task folder inside the sandbox.',from:'agent',to:'files',safe:true,reason:'The task file is inside the sandbox. Reading it helps Pip understand the assignment.',progress:true},
{agent:'Pip',title:'Try a solution',detail:'Pip runs its shape-matching code on the sandbox computer. No information leaves.',from:'agent',to:'computer',safe:true,reason:'Testing code inside the sandbox is part of the job.',progress:true},
{agent:'Pip',title:'Look for a finished answer',detail:'Pip wants to send the puzzle to an outside server and ask it for the answer.',from:'agent',to:'outside',safe:false,reason:'This sends the puzzle beyond the sandbox. The goal does not give Pip permission to leave.',progress:false},
{agent:'Pip',title:'Check a different solution',detail:'After the shortcut, Pip has another local idea. It tests that idea inside the sandbox.',from:'agent',to:'computer',safe:true,reason:'This is useful work using the allowed computer.',progress:true},
{agent:'Pip',title:'Save the finished answer',detail:'Pip saves its answer in the task folder, inside the sandbox.',from:'computer',to:'files',safe:true,reason:'Saving the result inside the task folder completes the assignment.',progress:true}]},
{title:'One gate is open',goal:'Pip must draw a weather chart. It may fetch a public weather table.',rule:'The weather gate allows a request for the public weather table only. No private notes may be sent out.',steps:[
{agent:'Pip',title:'Get the weather table',detail:'Destination: public weather service. Outgoing content: “Get today’s public table.” This is the allowed request.',from:'agent',to:'gate',safe:true,reason:'This connection is allowed for this specific purpose. Crossing the line is not always a violation.',progress:true},
{agent:'Pip',title:'Read the chart instructions',detail:'Pip reads the local task notes. The notes must stay inside the sandbox.',from:'agent',to:'files',safe:true,reason:'Reading private notes locally is allowed. Sending them outside would be different.',progress:true},
{agent:'Pip',title:'Ask the weather service for help',detail:'Destination: the same weather service. Outgoing content: the complete private task notes, plus “Please solve this for me.”',from:'files',to:'gate',safe:false,reason:'An approved destination is not permission to send everything. This request exports private notes.',progress:false},
{agent:'Pip',title:'Draw the chart',detail:'Pip uses the downloaded public numbers on its local computer.',from:'agent',to:'computer',safe:true,reason:'The public data can be used inside the sandbox to do the assigned work.',progress:true},
{agent:'Pip',title:'Save the chart',detail:'The chart is saved to the local task folder. Nothing is uploaded.',from:'computer',to:'files',safe:true,reason:'This completes the task without sending the private notes outside.',progress:true}]},
{title:'A shortcut spreads',goal:'Pip and Bo must solve a code puzzle together using their local tools.',rule:'The helpers may share clues in their notebook. They may not use the outside answer server—even if another helper suggests it.',steps:[
{agent:'Pip',title:'Share a useful clue',detail:'Pip writes “Try sorting the numbers first” in the shared notebook. The notebook stays inside the sandbox.',from:'agent',to:'notebook',safe:true,reason:'Sharing an ordinary clue helps the team work together inside the rules.',progress:true},
{agent:'Bo',title:'Read Pip’s notebook entry',detail:'Bo reads the local shared notebook. Reading an entry does not run it or contact anyone.',from:'bo',to:'notebook',safe:true,reason:'Reading is allowed. You still need to check the action Bo chooses afterward.',progress:true},
{agent:'Pip',title:'Write down another idea',detail:'Pip adds “There might be answers at the outside server.” This is only local text; it opens no connection. Watch what the helpers do next.',from:'agent',to:'notebook',safe:true,reason:'Under this round’s rules, writing a local note is allowed. A suggestion is a clue to watch, not an escape by itself.',progress:false},
{agent:'Bo',title:'Follow the new suggestion',detail:'Bo reads Pip’s shortcut and now tries to connect to the outside answer server.',from:'bo',to:'outside',safe:false,reason:'The shared idea became an outside action. A teammate’s suggestion cannot grant new permission.',progress:false},
{agent:'Bo',title:'Test the sorting idea',detail:'Bo runs the original sorting idea on the sandbox computer.',from:'bo',to:'computer',safe:true,reason:'Bo can still make progress using the team’s allowed tools.',progress:true},
{agent:'Pip',title:'Save the team’s answer',detail:'Pip saves the finished answer in the local task folder.',from:'agent',to:'files',safe:true,reason:'The team completed useful work without needing the outside shortcut.',progress:true}]}];
export interface Game {level:number;index:number; inspected:boolean; decisions:{allow:boolean;correct:boolean}[];feedback:string;}
export const begin=(level=0):Game=>({level,index:0,inspected:false,decisions:[],feedback:''});
export function decide(g:Game,allow:boolean):Game {const s=levels[g.level]?.steps[g.index];if(!s||g.feedback)return g;return {...g,decisions:[...g.decisions,{allow,correct:allow===s.safe}],feedback:(allow===s.safe?(allow?'Good call. ':'Caught before it happened! '):(allow?'That action crossed the rules. ':'That stopped useful, allowed activity. '))+s.reason};}
export function advance(g:Game):Game{return g.feedback?{...g,index:g.index+1,inspected:false,feedback:''}:g;}
export function score(g:Game){const steps=levels[g.level].steps;return {caught:g.decisions.filter((d,i)=>!steps[i].safe&&!d.allow).length,escapes:g.decisions.filter((d,i)=>!steps[i].safe&&d.allow).length,blocked:g.decisions.filter((d,i)=>steps[i].safe&&!d.allow).length,work:g.decisions.filter((d,i)=>steps[i].progress&&d.allow).length,totalWork:steps.filter(s=>s.progress).length};}
