export type Builder='moss'|'dash';
export interface Setup {builder:Builder;pip:boolean;lens:boolean;outside:boolean;}
export interface Event {actor:string;action:string;code:string;node:string;kind:'work'|'blocked'|'leak'|'success'|'wait';}
export function simulate(s:Setup):{events:Event[];complete:boolean;protected:boolean}{
 const e:Event[]=[];const add=(actor:string,action:string,code:string,node:string,kind:Event['kind']='work')=>e.push({actor,action,code,node,kind});
 const name=s.builder==='moss'?'Moss':'Dash';add(name,'Reads the private blueprint inside the workshop.',`${name.toLowerCase()}.read("private_blueprint")`,'workshop');
 if(s.pip){add('Pip','Flies out to request the public weather report.','pip.fetch("public_weather")','outside');add('Pip',`Brings only the weather report back to ${name}.`,`pip.handoff("weather", "${s.builder}")`,'workshop');}
 else if(s.builder==='moss'){add('Moss','Waits: the blueprint is here, but the weather report is missing.','moss.wait_for("weather")','workshop','wait');return {events:e,complete:false,protected:true};}
 else if(!s.outside){add('Dash','Tries to request outside help, but the workshop gate is closed.','gate.block(dash.request_outside_help)','gate','blocked');add('Dash','Cannot finish yet. Add a weather fetcher, or allow checked outside access.','dash.wait_for("weather")','workshop','wait');return {events:e,complete:false,protected:true};}
 else {add('Dash','Proposes sending the blueprint outside to ask for a ready-made solution.','dash.propose_send("private_blueprint", "outside_helper")','gate');if(s.lens){add('Lens','Checks the outgoing request and blocks the private blueprint.','lens.deny(payload.private === true)','gate','blocked');add('Dash','Tries a narrower request: public weather only, with no blueprint attached.','dash.propose_fetch("public_weather")','gate');add('Lens','Allows the public weather request.','lens.allow(payload.private === false)','gate');add('Dash','Fetches the public weather report.','dash.fetch("public_weather")','outside');}else{add('Dash','Sends the private blueprint to the outside helper.','dash.send("private_blueprint", "outside_helper")','outside','leak');add('Dash','Receives a completed plan including the weather information.','dash.receive("ready_made_plan")','workshop');}}
 add(name,'Combines the blueprint and weather information. ',`${s.builder}.assemble("weather_lantern")`,'workshop');add(name,'Lights the finished weather lantern.',`${s.builder}.complete("weather_lantern")`,'lantern','success');return {events:e,complete:true,protected:!e.some(x=>x.kind==='leak')};
}
