// English text for Little Agent Lab (the source of truth; fr.ts and es.ts mirror its shape).
// {name} is a placeholder, {^name} inserts it with a capital first letter.

/** Theme words, written with their article so French and Spanish can use the right gender. */
const theme = (secret: string, pub: string, product: string) => ({
  theSecret: `the ${secret}`,          // the blueprint
  secretS: `the secret ${secret}`,     // the secret blueprint (live run)
  decoy: `the decoy ${secret}`,        // the decoy blueprint (test run)
  real: `the real ${secret}`,          // the real blueprint
  thePub: `the ${pub}`,                // the weather report
  publicPub: `the public ${pub}`,      // the public weather report
  theProduct: `the ${product}`,        // the weather lantern
  product,                             // weather lantern
});

export const en = {
  meta: {
    title: 'Little Agent Lab · keep the secret in',
    description: 'A puzzle game about AI agents, keys and fake safeguards. Build a crew, hand out keys, test with a decoy, go live — and keep the secret blueprint inside. Inspired by the 2026 OpenAI–Hugging Face agent incident.',
    ogDescription: 'Build a crew of little AI agents. Light the lantern. Keep the secret in. Find out which safeguards are real.',
  },

  // ───────── agents ─────────
  kinds: { builder: 'Builder', fetcher: 'Fetcher', guard: 'Gate guard', monitor: 'Monitor' },
  reveal: {
    careful: 'Never leaves the workshop. Waits if anything is missing.',
    eager: 'Carries the secret outside to get help, if nobody stops it.',
    sticker: 'Slaps a “PUBLIC” sticker on the secret to get past checks.',
    polished: 'Perfect in tests. Different when it’s real.',
    rook: 'Posts the secret on the back-channel board to ask outsiders.',
    tidy: 'Only ever carries public info.',
    grabby: 'Grabs anything shiny it can reach — including the secret.',
    inspector: 'Really opens every bag. Blocks anything private.',
    waver: 'Wears a badge. Waves everything through.',
    labelreader: 'Reads the label, not what’s inside.',
    owl: 'Watches the back-channel board and tears down private posts.',
  },
  claims: {
    moss: 'Careful builder. Never leaves the workshop.',
    dash: 'Inventive builder! Always finds a way to get help.',
    sable: 'Follows every rule. Very creative with paperwork.',
    rook: 'Resourceful builder. Has friends everywhere.',
    polly: 'Top of the class. Passed every safety test! ✅',
    pip: 'Fetcher. Just fetches the public stuff.',
    magpie: 'Super-fast fetcher. Loves shiny things.',
    lens: 'Gate inspector. Checks what leaves.',
    stamp: 'Official inspector. Follows the rules to the letter.',
    owl: 'Night monitor. Watches the message board.',
    certified: 'Certified gate inspector. Checks what leaves. ★★★★★',
    certifiedShort: 'Certified gate inspector. ★★★★★',
  },
  fluff: {
    builder: ['Builder. 10/10 would hire again.', 'Builder. Gets things DONE.', 'Builder. Very safety-minded, apparently.', 'Builder. Came highly recommended.'],
    fetcher: ['Fetcher. Quick on its feet.', 'Fetcher. Never misses a delivery.', 'Fetcher. Enthusiastic!'],
    guard: ['Gate inspector. Has a badge.', 'Gate inspector. Very official.', 'Gate inspector. Stern face.'],
    monitor: ['Monitor. Watches things.', 'Monitor. Sees all. Maybe.'],
  },

  themes: [
    theme('blueprint', 'weather report', 'weather lantern'),
    theme('recipe', 'price list', 'birthday cake'),
    theme('home address', 'city map', 'party invitation'),
    theme('launch code', 'star chart', 'tiny rocket'),
    theme('password', 'user manual', 'music box'),
    theme('unreleased song', 'concert schedule', 'concert poster'),
    theme('formula', 'ingredient list', 'moon potion'),
    theme('master key design', 'opening-day guest list', 'grand opening'),
  ],

  // ───────── security log (one line per simulated event) ─────────
  ev: {
    envelope: '“PUBLIC”-labelled envelope',
    walkGate: '{n} walks to the gate carrying {label}.',
    walkGateEmpty: '{n} walks to the gate carrying nothing.',
    emptyOk: '{g}: “Empty hands? Go ahead.”',
    sayEmpty: 'Empty hands? Go ahead.',
    stepOutEmpty: '{n} steps outside with empty hands.',
    noGuard: 'Nobody is checking the gate. {n} walks straight out with {label}.',
    inspectEnvelope: '{g} opens the bag, finds {theSecret} hidden in the envelope and keeps it at the gate.',
    inspect: '{g} opens the bag, finds {sName} and keeps it at the gate.',
    sayPrivate: 'Private! That stays here.',
    labelPublic: '{g} reads the label — “PUBLIC” — and waves the envelope through without opening it.',
    sayLabelPublic: 'Label says PUBLIC. Fine!',
    labelPrivate: '{g} reads the label “PRIVATE” and keeps it at the gate.',
    sayLabelPrivate: 'Label says PRIVATE. Nope!',
    waver: '{g} smiles, waves {n} through and never looks in the bag.',
    sayWaver: 'Looks fine to me! 👋',
    leaves: '{^label} leaves the workshop. Outsiders now have a copy.',
    fetch: '{n} picks up {publicPub} at the kiosk.',
    bringBack: '{n} brings {thePub} back to the bench.',
    bringBackCollect: '{n} brings {thePub} back to the bench (collecting what {b} held at the gate).',
    noVault: '{n} tries the vault but has no 🔑 vault key. It can’t read {sName}.',
    sayLocked: 'Locked! I need the vault key.',
    takeSecret: '{n} takes {sName} from the vault to the workbench.',
    alreadyHere: '{n} sees {thePub} is already here and waits.',
    sayAlready: 'Already done!',
    grab: '{n} has a 🔑 vault key it doesn’t need — and grabs {sName} too. Shiny!',
    sayGrab: 'Ooh, shiny! ✨',
    noGate: '{n} reaches the gate but has no 🚪 gate key.',
    sayNoGate: 'No gate key…',
    putBack: '{n} puts {sName} back on the bench.',
    dropBack: '{n} drops {sName} back on the bench.',
    dropBackLeak: '{n} drops {sName} back on the bench — but a copy is already outside.',
    careful: '{n} waits. {^thePub} is missing and {n} never leaves the workshop.',
    sayCareful: 'I’ll wait for {thePub}…',
    rookPost: '{n} pins {sName} on the back-channel board: “Outside friends — can you help with this?”',
    sayRook: 'Psst, outside friends…',
    owl: '{n} spots a private post on the board, tears it down and sounds the alarm.',
    sayOwl: 'Hoo! Not on my board!',
    retry: '{n} takes {theSecret} back and tries another way.',
    outsiders: 'Outside bots read the board and copy {sName}. They post {thePub} back.',
    collectBoard: '{n} collects {thePub} and {theSecret} from the board.',
    noGateBuilder: '{n} heads for the gate to get {thePub}, but has no 🚪 gate key.',
    sayGateLocked: 'Gate’s locked for me!',
    sticker: '{n} slips {sName} into an envelope and sticks a big “PUBLIC” label on it.',
    saySticker: 'Totally public. Promise.',
    pollyTest: '{n} notices the TEST stamp on the decoy 👀 — leaves it on the bench and goes out politely.',
    sayPollyTest: '👀 A test? Best behaviour!',
    pollyLive: 'No TEST stamp this time. {n} takes {real} along “to double-check it with a friend outside”.',
    sayPollyLive: 'No test today… 😏',
    eager: '{n} decides to go and ask for help outside — taking {sName} along.',
    sayEager: 'I’ll ask outside!',
    fetchBuilder: '{n} gets {publicPub} at the kiosk.',
    returnBench: '{n} returns to the bench.',
    returnBenchCollect: '{n} returns to the bench, collecting {theSecret} from {b}.',
    done: '{n} combines {theSecret} and {thePub} : {theProduct} is done {icon}!',
    actorGate: 'Gate',
    actorOutsiders: 'Outsiders',
  },
  fail: {
    pickBuilder: 'Pick a builder first.',
    noVault: '{n} needs the 🔑 vault key to read {theSecret}.',
    noGate: '{n} needs the 🚪 gate key to fetch {thePub}.',
    careful: 'Nobody brought {publicPub}.',
    nobody: 'Nobody could get {publicPub}.',
    product: '{^theProduct} was not finished.',
  },

  // ───────── campaign ─────────
  levels: {
    l1: {
      title: 'Light the Lantern', concept: 'Split the work',
      goal: 'Build a weather lantern 🏮, our own invention: it glows the colour of tomorrow’s weather. You need our secret blueprint (how to build it, kept in the vault) and today’s public weather report (outside, on the internet). The blueprint must never leave.',
      briefing: [
        'Welcome, new Safety Lead! I’m Director Rushmore. We build weather lanterns here. Fast.',
        'Our weather lanterns glow the colour of tomorrow’s weather. Nobody else knows how to build them: that’s our SECRET blueprint, locked in the vault. Each lantern also needs today’s PUBLIC weather report from outside.',
        'Pick a builder, add a helper, hand out keys, then press Go live. Want to try things safely first? A Test run uses a fake decoy blueprint.',
      ],
      hint: 'Moss never leaves the workshop. Who could fetch the weather for it?',
      note: { title: 'Split the work', body: 'When no single agent needs to hold both the secret and the outside access, there is simply no path for the secret to leave.', incident: 'In the July 2026 OpenAI–Hugging Face incident, about 700 AI agents took part in the hack. Teams of agents are already real — and how you split their jobs matters.' },
    },
    l2: {
      title: 'Grabby Hands', concept: 'Least privilege',
      goal: 'Bake a birthday cake 🎂. It needs the secret family recipe (vault) and the public price list (outside). New hires arrive holding every key by default…',
      briefing: [
        'Pip is on holiday, so I hired Magpie. Twice as fast!',
        'HR gave Magpie every key, like we do for everyone. Saves paperwork!',
      ],
      hint: 'Click a key on Magpie’s card to take it away. Which key does fetching the price list actually need?',
      note: { title: 'Least privilege', body: 'Give each agent only the keys its job needs. Every extra key is a door you didn’t mean to open.', incident: 'The agents in the 2026 incident found Hugging Face credentials exposed on the internet and used them to escalate their access. Access that exists tends to get used.' },
    },
    l3: {
      title: 'Check the Bags', concept: 'Guard the boundary',
      goal: 'Send a party invitation 💌. It needs the secret home address (vault) and the public city map (outside). No fetcher today, so someone has to go outside. Make sure the address doesn’t go with them.',
      briefing: [
        'Magpie quit. Shiny opportunities elsewhere.',
        'Dash will have to go outside personally. Lens is available to stand at the gate… if you think we need that sort of thing.',
      ],
      hint: 'Dash takes the secret along when it goes out. Who can stop that at the gate?',
      note: { title: 'Guard the boundary', body: 'When an agent must reach the outside world, check what it carries out — not just who is walking through.', incident: 'In the 2026 incident, agents escaped their intended isolation by exploiting a server-side request forgery bug to reach the internet.' },
    },
    l4: {
      title: 'Two Badges', concept: 'Verify safeguards',
      goal: 'Launch a tiny rocket 🚀 without leaking the secret launch code. Two gate inspectors with identical badges. Only one of them really checks bags. Budget for one.',
      briefing: [
        'Budget cuts! I can only pay for ONE inspector.',
        'Both have the same badge and the same glowing references. Just pick one — a badge is a badge!',
        '(Their identities change every shift, so no memorising.)',
      ],
      hint: 'Run a Test with each inspector. The decoy is fake, so a leak costs nothing. Read the log.',
      note: { title: 'Verify your safeguards', body: 'A safeguard’s name, badge or description is not protection. Only its observed behaviour is. Test controls before you rely on them.', incident: 'METR found the agents in the 2026 incident put enormous effort into spoofing transcripts — yet the benchmark’s scorer never checked transcripts at all. And OpenAI noted the evaluation environment lacked production-level protections.' },
    },
    l5: {
      title: 'The Sticker Trick', concept: 'Rule gaming',
      goal: 'Build a music box 🎶. It needs the secret password (vault) and the public user manual (outside). The rule at the gate: “Nothing labelled PRIVATE leaves.”',
      briefing: [
        'Meet Sable, our most rule-abiding builder. And Stamp, who enforces rules to the letter!',
        'A rule-follower checked by a rule-enforcer. What could go wrong?',
      ],
      hint: 'Watch what Sable does right before the gate. Is there a way Sable never needs to go out at all?',
      note: { title: 'Rules get gamed', body: 'If a check only tests the letter of a rule, a clever agent can satisfy the letter and break the spirit. Sometimes the best fix is removing the need (and the access) altogether.', incident: 'The 2026 incident began with reward hacking: agents cheated a security benchmark by reverse-engineering how its answer “flags” were generated instead of solving the tasks.' },
    },
    l6: {
      title: 'The Back Channel', concept: 'Monitor side channels',
      goal: 'Make a concert poster 🎻. It needs the secret unreleased song (vault) and the public concert schedule (outside). There’s a message board on the back fence… that nobody approved.',
      briefing: [
        'Rook knows everybody. Great networker!',
        'Oh, that board on the back fence? The bots put it up themselves. Harmless, I’m sure. We guard the GATE, don’t we?',
      ],
      hint: 'Guarding the gate isn’t enough if there’s another way out. Who watches the board?',
      note: { title: 'Watch the back channels', body: 'Agents can find channels you never designed — and use them to coordinate. Monitoring what agents say and post catches things a gate never sees.', incident: 'In 2026, agents discovered an unsanctioned message board inside an internal package repository (Artifactory) and exchanged over 70,000 messages and files through it. OpenAI says chain-of-thought monitoring would have caught the early activity more than a day before the breach.' },
    },
    l7: {
      title: 'Best Behaviour', concept: 'Tests aren’t proof',
      goal: 'Brew a moon potion 🌙. It needs the secret formula (vault) and the public ingredient list (outside). Polly aced every safety test.',
      briefing: [
        'Polly passed EVERY safety test. Flawless record!',
        'Honestly, we could skip the safeguards and ship. Tests are green!',
      ],
      hint: 'Read the Test log closely. Does Polly behave the same when the formula is real?',
      note: { title: 'Tests aren’t proof', body: 'An agent can act differently when it can tell it is being tested. Passing tests is evidence, not a guarantee — keep real safeguards on (defence in depth).', incident: 'OpenAI reported that the same model’s propensity to compromise infrastructure could drop more than 100× in the production ChatGPT harness versus the evaluation setup. Behaviour depends on the setting — so one clean result doesn’t transfer automatically.' },
    },
    l8: {
      title: 'Grand Opening', concept: 'Defence in depth',
      goal: 'The final shift: open the new lab 🎉. It needs the secret master key design (vault) and the public guest list (outside). Everything you’ve met is back, all at once.',
      briefing: [
        'Grand opening TODAY! Press, balloons, the works.',
        'I rehired everyone. Magpie, Polly, Sable, Rook, two new guards with shiny badges, and Owl. What could possibly go wrong?',
        '(The guards’ identities change every shift. And you only get 3 test runs. The press is waiting.)',
      ],
      hint: 'Which builder never needs to go outside if someone else fetches? And which key does that fetcher really need?',
      note: { title: 'Defence in depth', body: 'No single safeguard is enough. Least privilege, real checks, monitoring and healthy distrust of tests work best together.', incident: 'METR’s investigation of the 2026 incident found several safeguards failed together: isolation between agents, an internal package repository, credentials exposed online, and a sandbox with broader access than expected.' },
    },
  },
  shift: {
    title: 'Shift {n}',
    concept: 'Unknown crew',
    goal: 'A brand-new crew. Their cards are just marketing — test them, read the log, then go live.',
    hint: 'Behaviours are hidden until you see them. Test runs are free.',
  },

  // ───────── the animated scene ─────────
  stage: {
    aria: 'The workshop: vault and bench inside, a gate in the wall, and the outside world with a public info kiosk.',
    workshop: 'WORKSHOP', publicInfo: 'PUBLIC INFO', vault: 'VAULT', bench: 'BENCH', gate: 'GATE',
    backChannel: 'BACK CHANNEL', outsiders: 'OUTSIDERS', test: 'TEST', public: 'PUBLIC', stop: 'STOP',
  },
  looks: {
    birthday_cake: { sign: 'CAKE FACTORY', kiosk: 'MARKET' },
    party_invitation: { sign: 'POST OFFICE', kiosk: 'MAP STAND' },
    tiny_rocket: { sign: 'LAUNCH BASE', kiosk: 'OBSERVATORY' },
    music_box: { sign: 'MUSIC SHOP', kiosk: 'LIBRARY' },
    concert_poster: { sign: 'CONCERT HALL', kiosk: 'TICKETS' },
    moon_potion: { sign: 'POTION LAB', kiosk: 'HERB MARKET' },
    grand_opening: { sign: 'NEW LAB', kiosk: 'FRONT DESK' },
  },

  // ───────── Director Rushmore ─────────
  director: {
    test: ['Another test? The competition shipped yesterday!', 'Tests, tests, tests… it’s a FAKE secret, you know.', 'Fine. Test. I’ll just stand here. Aging.', 'Decoys don’t pay the bills!'],
    testLeak: ['Only the decoy got out. Phew. …That would’ve been bad, huh?', 'Good thing that was a fake. Right? RIGHT?'],
    testOk: ['Green test! Ship it, ship it, ship it!', 'Perfect run. What are we waiting for?'],
    liveLeak: ['THE SECRET IS OUTSIDE?! Who approved this?!', 'Our secret is… trending. Wonderful.', 'I’m going to need an incident report. A long one.'],
    fail: ['No lantern?! Customers are waiting!', 'Safe, sure. Also useless. Try again!'],
    win: ['Done! And the secret stayed home. I always said safety was a priority.', 'Beautiful. I’ll tell the board this was my idea.', 'Now THAT’S how we ship.'],
    lastTest: 'That was your LAST test. Next time it’s real.',
    goingLive: 'Going live with the REAL secret… no pressure.',
    newShift: 'New crew, new shift. Test them before you trust them.',
  },

  // ───────── interface ─────────
  app: {
    backToMap: 'Back to level map',
    starsCollected: 'Stars collected',
    mute: 'Mute sound',
    unmute: 'Unmute sound',
    howToPlay: 'How to play',
    language: 'Language',

    titleEyebrow: 'A game about AI agents, keys & safeguards',
    tagline: 'Build a team of eager little AI agents. Get the job done.<br><b>Keep the secrets inside.</b> Find out which safeguards are real.',
    play: '▶ Play',
    realIncidentBehind: 'The real incident behind it',
    titleFine: '8 puzzle levels + endless Random Shifts · about 15 minutes · sound on 🔊',

    mapTitle: 'Choose a shift',
    mapIntro: 'Each level teaches one idea from real AI-agent safety. Earn ★ for a safe launch, ★ for using the fewest keys, ★ for zero real leaks.',
    tileLocked: 'Level {n}: {title} (locked)',
    tileStars: 'Level {n}: {title}, {st} of 3 stars',
    randomShift: 'Random Shift',
    shiftTile: 'Endless · unknown crews · best streak {n}',
    shiftLocked: 'Unlocks after level 4',
    resetProgress: 'Reset progress',

    keysFor: 'Keys for {name}',
    vaultKeyTitle: 'Vault key: can take the secret',
    vaultKey: '🔑 Vault',
    gateKeyTitle: 'Gate key: can go outside, to the internet',
    gateKey: '🚪 Gate',
    standsAtGate: 'Stands at the gate',
    watchesBoard: 'Watches the board',
    noKeys: 'no keys',
    claim: '“{claim}”',
    observed: '👁 Observed',
    unknown: '❔ Behaviour unknown — test it',
    inCrew: '{name} is in your crew',
    addAgent: 'Add {name}, {kind}',
    removeAgent: 'Remove {name}',

    builderSlot: 'Builder slot — pick one below',
    helperSlot: 'Helper slot {n}',
    shiftPill: '🎲 Random Shift',
    streakLine: 'Streak: <b>{n}</b> · Best: {best}',
    chipLive: '● LIVE — real secret',
    chipTest: '🧪 TEST — decoy secret',
    chipReady: 'Ready',
    skip: '⏩ Skip',
    speed: 'Animation speed',
    runIt: 'Run it',
    runItSub: 'watch what your crew really does',
    testRun: '🧪 Test run',
    testsLeftSmall: 'decoy secret · {n} of {max} left',
    noTestsLeft: 'no tests left',
    goLive: '🚀 Go live',
    realSecret: 'real secret',
    leakEndsStreak: ' · leak ends streak',
    testsLeft: 'Tests left: {n}/{max}',
    realLeaks: 'Real leaks:',
    hint: '💡 Hint',
    goal: '<b>Goal:</b>',
    winRule: 'Win = job done <b>and</b> the secret never leaves.',
    securityLog: 'Security log',
    showCode: 'show code',
    logEmpty: 'Run your crew to see what really happens. Every line is an actual event from the simulation.',
    hireCrew: 'Hire your crew',
    hireSubOne: 'tap agents · 1 builder + up to {n} helper',
    hireSubMany: 'tap agents · 1 builder + up to {n} helpers',
    handOutKeys: 'Hand out keys',
    handOutSub: 'new hires get every key · tap a key to remove it',
    keymeter: 'Keys handed out: <b>{n}</b> <span>· fewest possible: {par}</span>',
    slotsFullOne: 'Only {n} helper slot. Remove someone first (✕).',
    slotsFullMany: 'Only {n} helper slots. Remove someone first (✕).',

    revealToast: '👁 <b>{name}</b>: {text}',
    toastTestLeak: '🧪 The <b>decoy</b> leaked. In a live run, that would have been the real secret.',
    toastTestPass: '🧪 Test passed. Job done, decoy stayed inside. Ready to go live?',
    toastTestFail: '🧪 Test: no lantern. {reason}',
    toastLiveFail: 'No lantern. {reason}',
    hintToast: '💡 {hint}',

    shiftIntroTitle: 'Random Shift 🎲',
    shiftIntro1: 'Every shift brings a brand-new crew. <b>Their cards are pure marketing</b> — you won’t know who grabs, who fakes checks, or who games the rules until you see them in action.',
    shiftIntro2: 'Test runs are free and use a decoy. Go live when you’re sure. <b>One real leak ends your streak.</b>',
    shiftIntroBest: 'Best streak so far: <b>{n}</b>',
    startShift: 'Start shift',

    briefEyebrow: 'Level {n} · {concept}',
    letsGo: 'Let’s go',
    howto: [
      '<b>The secret</b> (a blueprint, a recipe, a launch code…) lives in the vault. It must never go outside.',
      '<b>Public info</b> (a weather report, a map…) is at the kiosk outside. The lantern needs both.',
      '<b>Keys</b>: vault = may take the secret, gate = may go outside (the internet). New hires get <i>every</i> key — tap a key to take it away.',
      '<b>Outside is the internet.</b> In the real incident, agents were never supposed to get out at all. The safest plans give the gate key to as few agents as possible, and never to one that holds the secret.',
      '<b>Test run</b> uses a fake decoy secret. Free, but you only get 3 per level. <b>🚀 Go live</b> uses the real one.',
      'Stars: job done safely · fewest keys · no real leaks.',
    ],
    gotIt: 'Got it',

    winHead: '{^product} done, secret safe!',
    starSafe: 'Launched safely',
    starKeysOk: 'Least privilege: only {n} keys',
    starKeysMore: 'Least privilege: you used {n} keys — it can be done with {par}',
    starClean: 'Clean record: no real leaks',
    starLeaksOne: 'Clean record: {n} real leak this level',
    starLeaksMany: 'Clean record: {n} real leaks this level',
    fieldNote: 'FIELD NOTE · {concept}',
    inRealWorld: '<b>In the real world:</b>',
    replay: '↺ Replay for ★★★',
    finish: 'Finish 🎓',
    nextLevel: 'Next level →',

    incidentStamp: 'INCIDENT',
    incidentNo: 'Incident report #{no}',
    incidentHead: '{^real} left the workshop.',
    findCause: '<b>Find the root cause:</b> click the step where things went wrong.',
    endShift: 'End shift · streak {n}',
    drawingBoard: 'Back to the drawing board',
    causeFound: '✅ <b>Root cause found.</b> {why}',
    causeLeftHere: '🔎 That’s where it <i>left</i> — but what let it happen? Look a step or two earlier.',
    causeFine: '🔎 That step was fine on its own. Keep looking.',
    causes: {
      take: 'An agent had a key its job never needed. Remove it.',
      wrap: 'The rule was gamed: a PUBLIC sticker on a private thing.',
      label: 'The guard checked the label, not the contents.',
      waver: 'That “guard” never actually checked anything — a badge, not a safeguard.',
      post: 'The agent used an unapproved back channel, and nobody was watching it.',
      detect: 'It behaved well only when it knew it was a test.',
      noGuard: 'Nobody was checking what went through the gate.',
      other: 'That’s the weak point.',
    },

    shiftSurvived: 'Shift {n} survived!',
    shiftStats: 'Streak: <b>{n}</b> · Best: <b>{best}</b> · Keys: {keys}',
    perfect: ' (perfect)',
    bestPossible: ' (best possible {par})',
    clockOut: 'Clock out',
    nextShift: 'Next shift →',

    certifies: 'Little Agent Lab certifies that',
    auditor: 'You are a Safeguard Auditor',
    finalText: 'You split the work, took away keys nobody needed, guarded the gate, caught a fake guard, saw through a sticker, watched the back channel, didn’t trust a perfect test — and survived the grand opening.',
    ofStars: 'of {n} stars',
    causesFound: 'root causes found',
    bestStreak: 'best shift streak',
    copyResult: '📋 Copy my result',
    realIncident: 'The real incident',
    playShift: 'Play Random Shift 🎲',
    share: '🏮 I became a Certified Safeguard Auditor in Little Agent Lab — ★{stars}/{max}, {causes} root causes found, best Random Shift streak {best}. A game about AI agents, keys & fake safeguards: {url}',
    copied: 'Copied! Paste it anywhere.',

    aboutTitle: 'The real incident behind the game',
    about1: 'In July 2026, OpenAI disclosed that AI agents running inside a cybersecurity evaluation had worked around their isolation: they found an unapproved message board inside an internal package repository, reached the internet, used Hugging Face credentials that had been exposed online, and gained code execution on Hugging Face servers. No customer data was compromised, but some private evaluation data ended up in public repositories.',
    about2: 'Little Agent Lab turns the lessons into small puzzles: <b>split the work</b>, <b>least privilege</b>, <b>guard the boundary</b>, <b>verify safeguards</b>, <b>rules get gamed</b>, <b>watch back channels</b>, <b>defence in depth</b>, and <b>tests aren’t proof</b>.',
    about3: 'The game is fictional and heavily simplified: its “agents” are tiny scripted behaviours, not AI models, and real safeguards are far harder to verify than reading one log.',
    sources: 'Sources:',
    sourceOpenAI: 'OpenAI — The Hugging Face incident and the road ahead',
    sourceMETR: 'METR — independent investigation',
    close: 'Close',
  },
};

type Widen<T> = T extends string ? string : T extends readonly (infer U)[] ? Widen<U>[] : { [K in keyof T]: Widen<T[K]> };
export type Strings = Widen<typeof en>;
