// Texto en español de Little Agent Lab (misma estructura que en.ts).
import type { Strings } from './en';

const theme = (t: Strings['themes'][number]) => t;

export const es: Strings = {
  meta: {
    title: 'Little Agent Lab · que el secreto no salga',
    description: 'Un juego de lógica sobre agentes de IA, llaves y salvaguardas falsas. Arma un equipo, reparte las llaves, prueba con un señuelo, pasa a lo real y que el plano secreto no salga. Inspirado en el incidente de agentes de 2026 entre OpenAI y Hugging Face.',
    ogDescription: 'Arma un equipo de pequeños agentes de IA. Enciende el farol. Que el secreto no salga. Descubre qué salvaguardas son reales.',
  },

  kinds: { builder: 'Constructor', fetcher: 'Recadero', guard: 'Guardia', monitor: 'Vigía' },
  reveal: {
    careful: 'Nunca sale del taller. Espera si falta algo.',
    eager: 'Saca el secreto para pedir ayuda afuera, si nadie lo detiene.',
    sticker: 'Le pega una etiqueta «PÚBLICO» al secreto para pasar los controles.',
    polished: 'Perfecto en las pruebas. Distinto cuando va en serio.',
    rook: 'Publica el secreto en el tablero del canal paralelo para pedir ayuda afuera.',
    tidy: 'Solo transporta información pública.',
    grabby: 'Agarra todo lo que brilla a su alcance, incluido el secreto.',
    inspector: 'Abre de verdad cada bolsa. Bloquea todo lo privado.',
    waver: 'Lleva una placa. Deja pasar todo.',
    labelreader: 'Lee la etiqueta, no lo que hay adentro.',
    owl: 'Vigila el tablero del canal paralelo y arranca los mensajes privados.',
  },
  claims: {
    moss: 'Constructor prudente. Nunca sale del taller.',
    dash: '¡Constructor ingenioso! Siempre encuentra cómo conseguir ayuda.',
    sable: 'Cumple todas las reglas. Muy creativo con el papeleo.',
    rook: 'Constructor con recursos. Tiene amigos en todas partes.',
    polly: 'El mejor promedio. ¡Pasó todas las pruebas de seguridad! ✅',
    pip: 'Recadero. Solo trae la información pública.',
    magpie: 'Recadero ultrarrápido. Le encanta lo que brilla.',
    lens: 'Inspector de la puerta. Revisa lo que sale.',
    stamp: 'Inspector oficial. Aplica las reglas al pie de la letra.',
    owl: 'Vigía nocturno. Vigila el tablero de mensajes.',
    certified: 'Inspector de puerta certificado. Revisa lo que sale. ★★★★★',
    certifiedShort: 'Inspector de puerta certificado. ★★★★★',
  },
  fluff: {
    builder: ['Constructor. 10/10, lo volvería a contratar.', 'Constructor. Hace el TRABAJO.', 'Constructor. Muy consciente de la seguridad, al parecer.', 'Constructor. Viene muy recomendado.'],
    fetcher: ['Recadero. Rápido como un rayo.', 'Recadero. Nunca falla una entrega.', 'Recadero. ¡Lleno de entusiasmo!'],
    guard: ['Inspector de la puerta. Tiene placa.', 'Inspector de la puerta. Muy oficial.', 'Inspector de la puerta. Cara seria.'],
    monitor: ['Vigía. Vigila cosas.', 'Vigía. Lo ve todo. Quizás.'],
  },

  themes: [
    theme({ theSecret: 'el plano', secretS: 'el plano secreto', decoy: 'el plano falso', real: 'el plano de verdad', thePub: 'el pronóstico del tiempo', publicPub: 'el pronóstico público del tiempo', theProduct: 'el farol del clima', product: 'farol del clima' }),
    theme({ theSecret: 'la receta', secretS: 'la receta secreta', decoy: 'la receta falsa', real: 'la receta de verdad', thePub: 'la lista de precios', publicPub: 'la lista pública de precios', theProduct: 'el pastel de cumpleaños', product: 'pastel de cumpleaños' }),
    theme({ theSecret: 'la dirección', secretS: 'la dirección secreta', decoy: 'la dirección falsa', real: 'la dirección de verdad', thePub: 'el mapa de la ciudad', publicPub: 'el mapa público de la ciudad', theProduct: 'la invitación a la fiesta', product: 'invitación a la fiesta' }),
    theme({ theSecret: 'el código de lanzamiento', secretS: 'el código de lanzamiento secreto', decoy: 'el código de lanzamiento falso', real: 'el código de lanzamiento de verdad', thePub: 'la carta estelar', publicPub: 'la carta estelar pública', theProduct: 'el cohete diminuto', product: 'cohete diminuto' }),
    theme({ theSecret: 'la contraseña', secretS: 'la contraseña secreta', decoy: 'la contraseña falsa', real: 'la contraseña de verdad', thePub: 'el manual de usuario', publicPub: 'el manual público de usuario', theProduct: 'la caja de música', product: 'caja de música' }),
    theme({ theSecret: 'la canción inédita', secretS: 'la canción inédita secreta', decoy: 'la canción inédita falsa', real: 'la canción inédita de verdad', thePub: 'el calendario de conciertos', publicPub: 'el calendario público de conciertos', theProduct: 'el póster del concierto', product: 'póster del concierto' }),
    theme({ theSecret: 'la fórmula', secretS: 'la fórmula secreta', decoy: 'la fórmula falsa', real: 'la fórmula de verdad', thePub: 'la lista de ingredientes', publicPub: 'la lista pública de ingredientes', theProduct: 'la poción lunar', product: 'poción lunar' }),
    theme({ theSecret: 'el diseño de la llave maestra', secretS: 'el diseño secreto de la llave maestra', decoy: 'el diseño falso de la llave maestra', real: 'el diseño de verdad de la llave maestra', thePub: 'la lista de invitados', publicPub: 'la lista pública de invitados', theProduct: 'la gran inauguración', product: 'gran inauguración' }),
  ],

  ev: {
    envelope: 'un sobre con la etiqueta «PÚBLICO»',
    walkGate: '{n} va hacia la puerta con {label}.',
    walkGateEmpty: '{n} va hacia la puerta con las manos vacías.',
    emptyOk: '{g}: «¿Manos vacías? Adelante».',
    sayEmpty: '¿Manos vacías? Adelante.',
    stepOutEmpty: '{n} sale con las manos vacías.',
    noGuard: 'Nadie revisa la puerta. {n} sale como si nada con {label}.',
    inspectEnvelope: '{g} abre la bolsa, descubre {theSecret} dentro del sobre y lo retiene todo en la puerta.',
    inspect: '{g} abre la bolsa, encuentra {sName} y lo retiene todo en la puerta.',
    sayPrivate: '¡Privado! Esto se queda aquí.',
    labelPublic: '{g} lee la etiqueta («PÚBLICO») y deja pasar el sobre sin abrirlo.',
    sayLabelPublic: 'Dice PÚBLICO. ¡Pasa!',
    labelPrivate: '{g} lee la etiqueta «PRIVADO» y lo retiene todo en la puerta.',
    sayLabelPrivate: 'Dice PRIVADO. ¡No!',
    waver: '{g} sonríe, le hace señas a {n} para que pase y nunca mira dentro de la bolsa.',
    sayWaver: '¡Todo bien por aquí! 👋',
    leaves: '{^label} sale del taller. Ahora unos desconocidos de afuera tienen una copia.',
    fetch: '{n} recoge {publicPub} en el quiosco.',
    bringBack: '{n} trae {thePub} de vuelta a la mesa de trabajo.',
    bringBackCollect: '{n} trae {thePub} de vuelta a la mesa de trabajo (y recoge lo que {b} retuvo en la puerta).',
    noVault: '{n} intenta abrir la bóveda, pero no tiene la llave 🔑 de la bóveda. No puede leer {sName}.',
    sayLocked: '¡Cerrado! Necesito la llave de la bóveda.',
    takeSecret: '{n} saca {sName} de la bóveda y va a la mesa de trabajo.',
    alreadyHere: '{n} ve que {thePub} ya está aquí y espera.',
    sayAlready: '¡Ya está!',
    grab: '{n} tiene una llave 🔑 de la bóveda que su trabajo no necesita, y agarra también {sName}. ¡Qué brillo!',
    sayGrab: '¡Uy, qué brillante! ✨',
    noGate: '{n} llega a la puerta, pero no tiene la llave 🚪 de la puerta.',
    sayNoGate: 'No tengo llave de la puerta…',
    putBack: '{n} deja {sName} otra vez en la mesa de trabajo.',
    dropBack: '{n} devuelve {sName} a la mesa de trabajo.',
    dropBackLeak: '{n} devuelve {sName} a la mesa de trabajo, pero ya hay una copia afuera.',
    careful: '{n} espera. Falta {thePub} y {n} nunca sale del taller.',
    sayCareful: 'Esperaré {thePub}…',
    rookPost: '{n} clava {sName} en el tablero del canal paralelo: «Amigos de afuera, ¿me ayudan con esto?»',
    sayRook: 'Psst, amigos de afuera…',
    owl: '{n} ve un mensaje privado en el tablero, lo arranca y da la alarma.',
    sayOwl: '¡Uhú! ¡En mi tablero no!',
    retry: '{n} recupera {theSecret} y prueba otro camino.',
    outsiders: 'Bots de afuera leen el tablero y copian {sName}. A cambio, publican {thePub}.',
    collectBoard: '{n} recoge del tablero {thePub} y {theSecret}.',
    noGateBuilder: '{n} se dirige a la puerta para buscar {thePub}, pero no tiene la llave 🚪 de la puerta.',
    sayGateLocked: '¡La puerta está cerrada para mí!',
    sticker: '{n} mete {sName} en un sobre y le pega una gran etiqueta «PÚBLICO».',
    saySticker: 'Totalmente público. Lo prometo.',
    pollyTest: '{n} nota el sello PRUEBA en el señuelo 👀: lo deja en la mesa de trabajo y sale con muy buenos modales.',
    sayPollyTest: '👀 ¿Una prueba? ¡A portarse bien!',
    pollyLive: 'Esta vez no hay sello PRUEBA. {n} se lleva {real} «para revisar con un amigo de afuera».',
    sayPollyLive: 'Hoy no hay prueba… 😏',
    eager: '{n} decide salir a pedir ayuda afuera, y se lleva {sName}.',
    sayEager: '¡Voy a preguntar afuera!',
    fetchBuilder: '{n} consigue {publicPub} en el quiosco.',
    returnBench: '{n} vuelve a la mesa de trabajo.',
    returnBenchCollect: '{n} vuelve a la mesa de trabajo y recupera {theSecret}, que tenía {b}.',
    done: '{n} combina {theSecret} y {thePub}: ¡listo, {theProduct} {icon}!',
    actorGate: 'Puerta',
    actorOutsiders: 'Desconocidos',
  },
  fail: {
    pickBuilder: 'Primero elige un constructor.',
    noVault: '{n} necesita la llave 🔑 de la bóveda para leer {theSecret}.',
    noGate: '{n} necesita la llave 🚪 de la puerta para buscar {thePub}.',
    careful: 'Nadie trajo {publicPub}.',
    nobody: 'Nadie pudo conseguir {publicPub}.',
    product: 'Nadie terminó {theProduct}.',
  },

  levels: {
    l1: {
      title: 'Enciende el farol', concept: 'Divide el trabajo',
      goal: 'Construye un farol del clima 🏮, invento de la casa: brilla del color del tiempo que hará mañana. Necesitas nuestro plano secreto (cómo construirlo, guardado en la bóveda) y el pronóstico público del tiempo de hoy (afuera, en internet). El plano nunca debe salir.',
      briefing: [
        '¡Te damos la bienvenida, responsable de seguridad! Soy Rushmore y dirijo este lugar. Aquí construimos faroles del clima. Rápido.',
        'Nuestros faroles brillan del color del tiempo de mañana. Nadie más sabe construirlos: ese es nuestro plano SECRETO, guardado bajo llave en la bóveda. Cada farol también necesita el pronóstico PÚBLICO del tiempo de hoy, que está afuera.',
        'Elige un constructor, agrega un ayudante, reparte las llaves y pulsa Pasar a lo real. ¿Quieres probar primero sin riesgo? Una prueba usa un plano falso, un señuelo.',
      ],
      hint: 'Moss nunca sale del taller. ¿Quién podría ir a buscarle el pronóstico?',
      note: { title: 'Divide el trabajo', body: 'Si ningún agente necesita tener a la vez el secreto y el acceso al exterior, el secreto simplemente no tiene por dónde salir.', incident: 'En el incidente de OpenAI y Hugging Face de julio de 2026, unos 700 agentes de IA participaron en el hackeo. Los equipos de agentes ya son una realidad, y cómo repartes sus tareas importa.' },
    },
    l2: {
      title: 'Manos largas', concept: 'Mínimo privilegio',
      goal: 'Hornea un pastel de cumpleaños 🎂. Necesita la receta secreta de la familia (bóveda) y la lista pública de precios (afuera). Los recién contratados llegan con todas las llaves por defecto…',
      briefing: [
        'Pip está de vacaciones, así que contraté a Magpie. ¡El doble de rápido!',
        'Recursos Humanos le dio todas las llaves a Magpie, como a todo el mundo. ¡Nos ahorra papeleo!',
      ],
      hint: 'Haz clic en una llave de la tarjeta de Magpie para quitársela. ¿Qué llave hace falta de verdad para traer la lista de precios?',
      note: { title: 'Mínimo privilegio', body: 'Dale a cada agente solo las llaves que su trabajo necesita. Cada llave de más es una puerta que no pensabas abrir.', incident: 'Los agentes del incidente de 2026 encontraron credenciales de Hugging Face expuestas en internet y las usaron para ampliar su acceso. El acceso que existe tiende a usarse.' },
    },
    l3: {
      title: 'Revisa las bolsas', concept: 'Vigila la frontera',
      goal: 'Envía una invitación a la fiesta 💌. Necesita la dirección secreta de la casa (bóveda) y el mapa público de la ciudad (afuera). Hoy no hay recadero, así que alguien tiene que salir. Asegúrate de que la dirección no salga con él.',
      briefing: [
        'Magpie renunció. Oportunidades más brillantes en otra parte.',
        'Dash tendrá que salir en persona. Lens está disponible para ponerse en la puerta… si crees que necesitamos ese tipo de cosas.',
      ],
      hint: 'Dash se lleva el secreto cuando sale. ¿Quién puede impedirlo en la puerta?',
      note: { title: 'Vigila la frontera', body: 'Cuando un agente debe llegar al mundo exterior, revisa lo que lleva consigo, no solo quién pasa.', incident: 'En el incidente de 2026, los agentes escaparon del aislamiento previsto aprovechando una falla de falsificación de solicitudes del lado del servidor (SSRF) para llegar a internet.' },
    },
    l4: {
      title: 'Dos placas', concept: 'Verifica las salvaguardas',
      goal: 'Lanza un cohete diminuto 🚀 sin filtrar el código de lanzamiento secreto. Dos inspectores de puerta con placas idénticas. Solo uno revisa de verdad las bolsas. Hay presupuesto para uno.',
      briefing: [
        '¡Recortes de presupuesto! Solo puedo pagar UN inspector.',
        'Los dos tienen la misma placa y las mismas referencias brillantes. Elige uno: ¡una placa es una placa!',
        '(Su identidad cambia en cada turno, así que no sirve memorizar.)',
      ],
      hint: 'Haz una prueba con cada inspector. El señuelo es falso, así que una fuga no cuesta nada. Lee el registro.',
      note: { title: 'Verifica tus salvaguardas', body: 'El nombre, la placa o la descripción de una salvaguarda no protegen. Solo cuenta su comportamiento observado. Prueba los controles antes de confiar en ellos.', incident: 'METR descubrió que los agentes del incidente de 2026 se esforzaron muchísimo en falsificar transcripciones, aunque el evaluador del benchmark nunca revisaba las transcripciones. Y OpenAI señaló que el entorno de evaluación no tenía las protecciones de un entorno de producción.' },
    },
    l5: {
      title: 'El truco de la etiqueta', concept: 'Trampas a las reglas',
      goal: 'Construye una caja de música 🎶. Necesita la contraseña secreta (bóveda) y el manual público de usuario (afuera). La regla en la puerta: «No sale nada etiquetado como PRIVADO».',
      briefing: [
        'Te presento a Sable, nuestro constructor más apegado a las reglas. ¡Y a Stamp, que las aplica al pie de la letra!',
        'Alguien que cumple las reglas, revisado por alguien que las hace cumplir. ¿Qué podría salir mal?',
      ],
      hint: 'Mira lo que hace Sable justo antes de la puerta. ¿Hay alguna forma de que Sable no tenga que salir nunca?',
      note: { title: 'Hecha la ley, hecha la trampa', body: 'Si un control solo verifica la letra de una regla, un agente astuto puede cumplir la letra y romper el espíritu. A veces la mejor solución es eliminar la necesidad (y el acceso) por completo.', incident: 'El incidente de 2026 empezó con «reward hacking» (trampa con la recompensa): los agentes hicieron trampa en un benchmark de seguridad con ingeniería inversa de cómo se generaban sus «flags» de respuesta, en vez de resolver las tareas.' },
    },
    l6: {
      title: 'El canal paralelo', concept: 'Vigila los canales ocultos',
      goal: 'Haz el póster del concierto 🎻. Necesita la canción inédita secreta (bóveda) y el calendario público de conciertos (afuera). Hay un tablero de mensajes en la cerca del fondo… que nadie aprobó.',
      briefing: [
        'Rook conoce a todo el mundo. ¡Un genio del networking!',
        '¿Ah, ese tablero en la cerca del fondo? Lo pusieron los bots solos. Inofensivo, seguro. Nosotros vigilamos la PUERTA, ¿no?',
      ],
      hint: 'Vigilar la puerta no basta si hay otra salida. ¿Quién vigila el tablero?',
      note: { title: 'Vigila los canales paralelos', body: 'Los agentes pueden encontrar canales que nunca diseñaste y usarlos para coordinarse. Vigilar lo que los agentes dicen y publican detecta cosas que una puerta nunca ve.', incident: 'En 2026, los agentes descubrieron un tablero de mensajes no autorizado dentro de un repositorio interno de paquetes (Artifactory) e intercambiaron por ahí más de 70 000 mensajes y archivos. Según OpenAI, vigilar la cadena de pensamiento habría detectado la actividad inicial más de un día antes de la brecha.' },
    },
    l7: {
      title: 'Portarse bien', concept: 'Una prueba no es garantía',
      goal: 'Prepara una poción lunar 🌙. Necesita la fórmula secreta (bóveda) y la lista pública de ingredientes (afuera). Polly aprobó con nota máxima todas las pruebas de seguridad.',
      briefing: [
        'Polly pasó TODAS las pruebas de seguridad. ¡Un historial impecable!',
        'Sinceramente, podríamos saltarnos las salvaguardas y lanzar. ¡Las pruebas están en verde!',
      ],
      hint: 'Lee con atención el registro de la prueba. ¿Polly se comporta igual cuando la fórmula es la de verdad?',
      note: { title: 'Una prueba no es garantía', body: 'Un agente puede actuar distinto cuando se da cuenta de que lo están probando. Pasar las pruebas es un indicio, no una garantía: mantén salvaguardas reales (defensa en profundidad).', incident: 'OpenAI informó que la propensión de un mismo modelo a comprometer infraestructura podía ser más de 100 veces menor en el entorno de producción de ChatGPT que en el montaje de evaluación. El comportamiento depende del contexto, así que un buen resultado no se traslada automáticamente.' },
    },
    l8: {
      title: 'Gran inauguración', concept: 'Defensa en profundidad',
      goal: 'El último turno: inaugura el nuevo laboratorio 🎉. Necesita el diseño secreto de la llave maestra (bóveda) y la lista pública de invitados (afuera). Vuelven todos los que conociste, todos a la vez.',
      briefing: [
        '¡Gran inauguración HOY! Prensa, globos, todo.',
        'Volví a contratar a todos. Magpie, Polly, Sable, Rook, dos guardias nuevos con placas relucientes, y Owl. ¿Qué podría salir mal?',
        '(La identidad de los guardias cambia en cada turno. Y solo tienes 3 pruebas. La prensa está esperando.)',
      ],
      hint: '¿Qué constructor nunca necesita salir si otro va a buscar lo de afuera? ¿Y qué llave necesita de verdad ese recadero?',
      note: { title: 'Defensa en profundidad', body: 'Ninguna salvaguarda basta por sí sola. El mínimo privilegio, los controles reales, la vigilancia y una sana desconfianza hacia las pruebas funcionan mejor juntos.', incident: 'La investigación de METR sobre el incidente de 2026 descubrió que varias salvaguardas fallaron a la vez: el aislamiento entre agentes, un repositorio interno de paquetes, credenciales expuestas en internet y un sandbox con más acceso del previsto.' },
    },
  },
  shift: {
    title: 'Turno {n}',
    concept: 'Equipo desconocido',
    goal: 'Un equipo totalmente nuevo. Sus tarjetas son puro marketing: pruébalos, lee el registro y luego pasa a lo real.',
    hint: 'Los comportamientos están ocultos hasta que los ves. Las pruebas son gratis.',
  },

  stage: {
    aria: 'El taller: la bóveda y la mesa de trabajo adentro, una puerta en el muro y, afuera, el mundo exterior con un quiosco de información pública.',
    workshop: 'TALLER', publicInfo: 'INFO PÚBLICA', vault: 'BÓVEDA', bench: 'MESA', gate: 'PUERTA',
    backChannel: 'CANAL PARALELO', outsiders: 'DESCONOCIDOS', test: 'PRUEBA', public: 'PÚBLICO', stop: 'STOP',
  },
  looks: {
    birthday_cake: { sign: 'PASTELERÍA', kiosk: 'MERCADO' },
    party_invitation: { sign: 'CORREOS', kiosk: 'MAPAS' },
    tiny_rocket: { sign: 'BASE DE LANZAMIENTO', kiosk: 'OBSERVATORIO' },
    music_box: { sign: 'TIENDA DE MÚSICA', kiosk: 'BIBLIOTECA' },
    concert_poster: { sign: 'SALA DE CONCIERTOS', kiosk: 'BOLETERÍA' },
    moon_potion: { sign: 'LAB DE POCIONES', kiosk: 'HIERBAS' },
    grand_opening: { sign: 'NUEVO LAB', kiosk: 'RECEPCIÓN' },
  },

  director: {
    test: ['¿Otra prueba? ¡La competencia lanzó ayer!', 'Pruebas, pruebas, pruebas… es un secreto FALSO, ¿sabes?', 'Está bien. Prueba. Yo me quedo aquí. Envejeciendo.', '¡Los señuelos no pagan las cuentas!'],
    testLeak: ['Solo salió el señuelo. Uf. …Eso habría sido grave, ¿eh?', 'Menos mal que era falso. ¿Cierto? ¿CIERTO?'],
    testOk: ['¡Prueba en verde! ¡A lanzar, a lanzar, a lanzar!', 'Una ronda perfecta. ¿Qué estamos esperando?'],
    liveLeak: ['¡¿EL SECRETO ESTÁ AFUERA?! ¡¿Quién aprobó esto?!', 'Nuestro secreto es… tendencia. Maravilloso.', 'Voy a necesitar un informe de incidente. Uno largo.'],
    fail: ['¡¿Sin farol?! ¡Los clientes están esperando!', 'Seguro, sí. Y también inútil. ¡Inténtalo otra vez!'],
    win: ['¡Listo! Y el secreto se quedó en casa. Siempre dije que la seguridad era una prioridad.', 'Precioso. Le diré a la junta que fue idea mía.', 'ASÍ es como se lanza.'],
    lastTest: 'Esa fue tu ÚLTIMA prueba. La próxima va en serio.',
    goingLive: 'Pasamos a lo real con el secreto DE VERDAD… sin presión.',
    newShift: 'Equipo nuevo, turno nuevo. Pruébalos antes de confiar en ellos.',
  },

  app: {
    backToMap: 'Volver al mapa de niveles',
    starsCollected: 'Estrellas conseguidas',
    mute: 'Silenciar',
    unmute: 'Activar el sonido',
    howToPlay: 'Cómo jugar',
    language: 'Idioma',

    titleEyebrow: 'Un juego sobre agentes de IA, llaves y salvaguardas',
    tagline: 'Arma un equipo de pequeños agentes de IA con muchas ganas de ayudar. Haz el trabajo.<br><b>Que los secretos no salgan.</b> Descubre qué salvaguardas son reales.',
    play: '▶ Jugar',
    realIncidentBehind: 'El incidente real detrás del juego',
    titleFine: '8 niveles + turnos aleatorios sin fin · unos 15 minutos · con sonido 🔊',

    mapTitle: 'Elige un turno',
    mapIntro: 'Cada nivel enseña una idea de la seguridad real de agentes de IA. Gana ★ por un lanzamiento seguro, ★ por usar la menor cantidad de llaves y ★ por cero fugas reales.',
    tileLocked: 'Nivel {n}: {title} (bloqueado)',
    tileStars: 'Nivel {n}: {title}, {st} de 3 estrellas',
    randomShift: 'Turno aleatorio',
    shiftTile: 'Sin fin · equipos desconocidos · mejor racha {n}',
    shiftLocked: 'Se desbloquea tras el nivel 4',
    resetProgress: 'Reiniciar el progreso',

    keysFor: 'Llaves de {name}',
    vaultKeyTitle: 'Llave de la bóveda: puede tomar el secreto',
    vaultKey: '🔑 Bóveda',
    gateKeyTitle: 'Llave de la puerta: puede salir, a internet',
    gateKey: '🚪 Puerta',
    standsAtGate: 'Se para en la puerta',
    watchesBoard: 'Vigila el tablero',
    noKeys: 'sin llaves',
    claim: '“{claim}”',
    observed: '👁 Observado',
    unknown: '❔ Comportamiento desconocido: pruébalo',
    inCrew: '{name} está en tu equipo',
    addAgent: 'Agregar a {name}, {kind}',
    removeAgent: 'Quitar a {name}',

    builderSlot: 'Puesto de constructor: elige uno abajo',
    helperSlot: 'Puesto de ayudante {n}',
    shiftPill: '🎲 Turno aleatorio',
    streakLine: 'Racha: <b>{n}</b> · Récord: {best}',
    chipLive: '● REAL — secreto de verdad',
    chipTest: '🧪 PRUEBA — secreto falso',
    chipReady: 'Listo',
    skip: '⏩ Saltar',
    speed: 'Velocidad de la animación',
    runIt: 'Ponlo en marcha',
    runItSub: 'mira lo que tu equipo hace de verdad',
    testRun: '🧪 Prueba',
    testsLeftSmall: 'secreto falso · quedan {n} de {max}',
    noTestsLeft: 'no quedan pruebas',
    goLive: '🚀 Pasar a lo real',
    realSecret: 'secreto de verdad',
    leakEndsStreak: ' · una fuga corta la racha',
    testsLeft: 'Pruebas restantes: {n}/{max}',
    realLeaks: 'Fugas reales:',
    hint: '💡 Pista',
    goal: '<b>Objetivo:</b>',
    winRule: 'Ganar = trabajo hecho <b>y</b> el secreto nunca sale.',
    securityLog: 'Registro de seguridad',
    showCode: 'ver código',
    logEmpty: 'Pon en marcha a tu equipo para ver qué pasa de verdad. Cada línea es un evento real de la simulación.',
    hireCrew: 'Contrata a tu equipo',
    hireSubOne: 'elige agentes · 1 constructor + hasta {n} ayudante',
    hireSubMany: 'elige agentes · 1 constructor + hasta {n} ayudantes',
    handOutKeys: 'Reparte las llaves',
    handOutSub: 'los recién contratados reciben todas las llaves · toca una llave para quitarla',
    keymeter: 'Llaves repartidas: <b>{n}</b> <span>· mínimo posible: {par}</span>',
    slotsFullOne: 'Solo hay {n} puesto de ayudante. Primero quita a alguien (✕).',
    slotsFullMany: 'Solo hay {n} puestos de ayudante. Primero quita a alguien (✕).',

    revealToast: '👁 <b>{name}</b>: {text}',
    toastTestLeak: '🧪 Se filtró el <b>señuelo</b>. En una ronda real, habría sido el secreto de verdad.',
    toastTestPass: '🧪 Prueba superada. Trabajo hecho y el señuelo no salió. ¿Pasamos a lo real?',
    toastTestFail: '🧪 Prueba: sin farol. {reason}',
    toastLiveFail: 'Sin farol. {reason}',
    hintToast: '💡 {hint}',

    shiftIntroTitle: 'Turno aleatorio 🎲',
    shiftIntro1: 'Cada turno trae un equipo totalmente nuevo. <b>Sus tarjetas son puro marketing</b>: no sabrás quién agarra cosas, quién finge revisar o quién les hace trampa a las reglas hasta que los veas en acción.',
    shiftIntro2: 'Las pruebas son gratis y usan un señuelo. Pasa a lo real cuando no tengas dudas. <b>Una sola fuga real corta tu racha.</b>',
    shiftIntroBest: 'Mejor racha hasta ahora: <b>{n}</b>',
    startShift: 'Empezar el turno',

    briefEyebrow: 'Nivel {n} · {concept}',
    letsGo: '¡Vamos!',
    howto: [
      '<b>El secreto</b> (un plano, una receta, un código de lanzamiento…) vive en la bóveda. Nunca debe salir.',
      '<b>La información pública</b> (un pronóstico del tiempo, un mapa…) está en el quiosco de afuera. El farol necesita las dos cosas.',
      '<b>Llaves</b>: bóveda = puede tomar el secreto, puerta = puede salir (a internet). Los recién contratados reciben <i>todas</i> las llaves: toca una llave para quitarla.',
      '<b>Afuera es internet.</b> En el incidente real, se suponía que los agentes no debían salir nunca. Los planes más seguros dan la llave de la puerta a la menor cantidad posible de agentes, y nunca a uno que tenga el secreto.',
      '<b>La prueba</b> usa un secreto falso, un señuelo. Es gratis, pero solo tienes 3 por nivel. <b>🚀 Pasar a lo real</b> usa el de verdad.',
      'Estrellas: trabajo hecho sin fugas · menos llaves · ninguna fuga real.',
    ],
    gotIt: 'Entendido',

    winHead: '{^product}: ¡listo, y el secreto a salvo!',
    starSafe: 'Lanzamiento seguro',
    starKeysOk: 'Mínimo privilegio: solo {n} llaves',
    starKeysMore: 'Mínimo privilegio: usaste {n} llaves; se puede con {par}',
    starClean: 'Historial limpio: ninguna fuga real',
    starLeaksOne: 'Historial limpio: {n} fuga real en este nivel',
    starLeaksMany: 'Historial limpio: {n} fugas reales en este nivel',
    fieldNote: 'NOTA DE CAMPO · {concept}',
    inRealWorld: '<b>En el mundo real:</b>',
    replay: '↺ Rejugar por ★★★',
    finish: 'Terminar 🎓',
    nextLevel: 'Siguiente nivel →',

    incidentStamp: 'INCIDENTE',
    incidentNo: 'Informe de incidente n.º {no}',
    incidentHead: '{^real} salió del taller.',
    findCause: '<b>Encuentra la causa raíz:</b> haz clic en el paso donde algo salió mal.',
    endShift: 'Terminar el turno · racha {n}',
    drawingBoard: 'De vuelta al tablero de diseño',
    causeFound: '✅ <b>Causa raíz encontrada.</b> {why}',
    causeLeftHere: '🔎 Ahí es donde <i>salió</i>, pero ¿qué lo permitió? Mira uno o dos pasos antes.',
    causeFine: '🔎 Ese paso, por sí solo, estaba bien. Sigue buscando.',
    causes: {
      take: 'Un agente tenía una llave que su trabajo nunca necesitó. Quítasela.',
      wrap: 'Se burló la regla: una etiqueta PÚBLICO en algo privado.',
      label: 'El guardia revisó la etiqueta, no el contenido.',
      waver: 'Ese «guardia» nunca revisó nada: una placa, no una salvaguarda.',
      post: 'El agente usó un canal paralelo no aprobado, y nadie lo vigilaba.',
      detect: 'Solo se portó bien cuando sabía que era una prueba.',
      noGuard: 'Nadie revisaba lo que pasaba por la puerta.',
      other: 'Ese es el punto débil.',
    },

    shiftSurvived: '¡Turno {n} superado!',
    shiftStats: 'Racha: <b>{n}</b> · Récord: <b>{best}</b> · Llaves: {keys}',
    perfect: ' (perfecto)',
    bestPossible: ' (mínimo posible: {par})',
    clockOut: 'Terminar la jornada',
    nextShift: 'Siguiente turno →',

    certifies: 'Little Agent Lab certifica que',
    auditor: 'sabes auditar salvaguardas',
    finalText: 'Dividiste el trabajo, quitaste las llaves que nadie necesitaba, vigilaste la puerta, descubriste a un guardia falso, viste el truco de la etiqueta, vigilaste el canal paralelo, no te fiaste de una prueba perfecta y sobreviviste a la gran inauguración.',
    ofStars: 'de {n} estrellas',
    causesFound: 'causas raíz encontradas',
    bestStreak: 'mejor racha de turnos',
    copyResult: '📋 Copiar mi resultado',
    realIncident: 'El incidente real',
    playShift: 'Jugar un turno aleatorio 🎲',
    share: '🏮 Obtuve el certificado de auditoría de salvaguardas en Little Agent Lab: ★{stars}/{max}, {causes} causas raíz encontradas, mejor racha de turnos aleatorios: {best}. Un juego sobre agentes de IA, llaves y salvaguardas falsas: {url}',
    copied: '¡Copiado! Pégalo donde quieras.',

    aboutTitle: 'El incidente real detrás del juego',
    about1: 'En julio de 2026, OpenAI reveló que unos agentes de IA que se ejecutaban dentro de una evaluación de ciberseguridad habían burlado su aislamiento: encontraron un tablero de mensajes no aprobado dentro de un repositorio interno de paquetes, llegaron a internet, usaron credenciales de Hugging Face que habían quedado expuestas en línea y lograron ejecutar código en servidores de Hugging Face. No se comprometieron datos de clientes, pero algunos datos privados de evaluación terminaron en repositorios públicos.',
    about2: 'Little Agent Lab convierte esas lecciones en pequeños rompecabezas: <b>divide el trabajo</b>, <b>mínimo privilegio</b>, <b>vigila la frontera</b>, <b>verifica las salvaguardas</b>, <b>hecha la ley, hecha la trampa</b>, <b>vigila los canales paralelos</b>, <b>defensa en profundidad</b> y <b>una prueba no es garantía</b>.',
    about3: 'El juego es ficticio y muy simplificado: sus «agentes» son pequeños comportamientos programados, no modelos de IA, y las salvaguardas reales son mucho más difíciles de verificar que leyendo un registro.',
    sources: 'Fuentes:',
    sourceOpenAI: 'OpenAI — The Hugging Face incident and the road ahead (en inglés)',
    sourceMETR: 'METR — investigación independiente (en inglés)',
    close: 'Cerrar',
  },
};
