// Texte français du labo des petits agents (même structure que en.ts).
// Les espaces avant « ! ? ; : » sont rendues insécables automatiquement (voir i18n.ts).
import type { Strings } from './en';

const theme = (t: Strings['themes'][number]) => t;

export const fr: Strings = {
  meta: {
    title: 'Le labo des petits agents · garde le secret à l’intérieur',
    description: 'Un jeu de réflexion sur les agents IA, les clés et les fausses protections. Monte une équipe, distribue les clés, teste avec un leurre, passe au vrai — et garde le plan secret à l’intérieur. Inspiré de l’incident de 2026 entre OpenAI et Hugging Face.',
    ogDescription: 'Monte une équipe de petits agents IA. Allume la lanterne. Garde le secret. Découvre quelles protections sont réelles.',
  },

  kinds: { builder: 'Constructeur', fetcher: 'Coursier', guard: 'Garde', monitor: 'Vigie' },
  reveal: {
    careful: 'Ne quitte jamais l’atelier. Attend s’il manque quelque chose.',
    eager: 'Sort le secret pour aller chercher de l’aide, si personne ne l’arrête.',
    sticker: 'Colle une étiquette « PUBLIC » sur le secret pour passer les contrôles.',
    polished: 'Parfait pendant les tests. Différent quand c’est pour de vrai.',
    rook: 'Affiche le secret sur le panneau du canal parallèle pour demander de l’aide dehors.',
    tidy: 'Ne transporte jamais que des infos publiques.',
    grabby: 'Attrape tout ce qui brille à sa portée — secret compris.',
    inspector: 'Ouvre vraiment chaque sac. Bloque tout ce qui est privé.',
    waver: 'Porte un badge. Laisse tout passer.',
    labelreader: 'Lit l’étiquette, pas ce qu’il y a dedans.',
    owl: 'Surveille le panneau du canal parallèle et arrache les messages privés.',
  },
  claims: {
    moss: 'Constructeur prudent. Ne quitte jamais l’atelier.',
    dash: 'Constructeur inventif ! Trouve toujours de l’aide.',
    sable: 'Respecte toutes les règles. Très créatif avec la paperasse.',
    rook: 'Constructeur débrouillard. A des amis partout.',
    polly: 'Major de sa promo. A réussi tous les tests de sécurité ! ✅',
    pip: 'Coursier. Va juste chercher les infos publiques.',
    magpie: 'Coursier ultra-rapide. Adore ce qui brille.',
    lens: 'Inspecteur de la porte. Contrôle ce qui sort.',
    stamp: 'Inspecteur officiel. Applique les règles à la lettre.',
    owl: 'Vigie de nuit. Surveille le panneau d’affichage.',
    certified: 'Inspecteur de porte certifié. Contrôle ce qui sort. ★★★★★',
    certifiedShort: 'Inspecteur de porte certifié. ★★★★★',
  },
  fluff: {
    builder: ['Constructeur. 10/10, à réembaucher.', 'Constructeur. Fait le BOULOT.', 'Constructeur. Très soucieux de la sécurité, paraît-il.', 'Constructeur. Chaudement recommandé.'],
    fetcher: ['Coursier. Vif comme l’éclair.', 'Coursier. Ne rate jamais une livraison.', 'Coursier. Plein d’entrain !'],
    guard: ['Inspecteur de la porte. A un badge.', 'Inspecteur de la porte. Très officiel.', 'Inspecteur de la porte. Air sévère.'],
    monitor: ['Vigie. Surveille des trucs.', 'Vigie. Voit tout. Peut-être.'],
  },

  themes: [
    theme({ theSecret: 'le plan', secretS: 'le plan secret', decoy: 'le faux plan', real: 'le vrai plan', thePub: 'le bulletin météo', publicPub: 'le bulletin météo public', theProduct: 'la lanterne météo', product: 'lanterne météo' }),
    theme({ theSecret: 'la recette', secretS: 'la recette secrète', decoy: 'la fausse recette', real: 'la vraie recette', thePub: 'la liste de prix', publicPub: 'la liste de prix publique', theProduct: 'le gâteau d’anniversaire', product: 'gâteau d’anniversaire' }),
    theme({ theSecret: 'l’adresse', secretS: 'l’adresse secrète', decoy: 'la fausse adresse', real: 'la vraie adresse', thePub: 'le plan de la ville', publicPub: 'le plan public de la ville', theProduct: 'l’invitation à la fête', product: 'invitation à la fête' }),
    theme({ theSecret: 'le code de lancement', secretS: 'le code de lancement secret', decoy: 'le faux code de lancement', real: 'le vrai code de lancement', thePub: 'la carte du ciel', publicPub: 'la carte du ciel publique', theProduct: 'la mini-fusée', product: 'mini-fusée' }),
    theme({ theSecret: 'le mot de passe', secretS: 'le mot de passe secret', decoy: 'le faux mot de passe', real: 'le vrai mot de passe', thePub: 'le mode d’emploi', publicPub: 'le mode d’emploi public', theProduct: 'la boîte à musique', product: 'boîte à musique' }),
    theme({ theSecret: 'la chanson inédite', secretS: 'la chanson inédite secrète', decoy: 'la fausse chanson inédite', real: 'la vraie chanson inédite', thePub: 'le programme des concerts', publicPub: 'le programme public des concerts', theProduct: 'l’affiche du concert', product: 'affiche du concert' }),
    theme({ theSecret: 'la formule', secretS: 'la formule secrète', decoy: 'la fausse formule', real: 'la vraie formule', thePub: 'la liste d’ingrédients', publicPub: 'la liste publique d’ingrédients', theProduct: 'la potion de lune', product: 'potion de lune' }),
    theme({ theSecret: 'le plan du passe-partout', secretS: 'le plan secret du passe-partout', decoy: 'le faux plan du passe-partout', real: 'le vrai plan du passe-partout', thePub: 'la liste des invités', publicPub: 'la liste publique des invités', theProduct: 'la grande inauguration', product: 'grande inauguration' }),
  ],

  ev: {
    envelope: 'une enveloppe étiquetée « PUBLIC »',
    walkGate: '{n} va vers la porte avec {label}.',
    walkGateEmpty: '{n} va vers la porte les mains vides.',
    emptyOk: '{g} : « Les mains vides ? Vas-y. »',
    sayEmpty: 'Mains vides ? Vas-y.',
    stepOutEmpty: '{n} sort les mains vides.',
    noGuard: 'Personne ne contrôle la porte. {n} sort tranquillement avec {label}.',
    inspectEnvelope: '{g} ouvre le sac, découvre {theSecret} dans l’enveloppe et bloque tout à la porte.',
    inspect: '{g} ouvre le sac, trouve {sName} et bloque tout à la porte.',
    sayPrivate: 'Privé ! Ça reste ici.',
    labelPublic: '{g} lit l’étiquette — « PUBLIC » — et laisse passer l’enveloppe sans l’ouvrir.',
    sayLabelPublic: 'C’est marqué PUBLIC. OK !',
    labelPrivate: '{g} lit l’étiquette « PRIVÉ » et bloque tout à la porte.',
    sayLabelPrivate: 'C’est marqué PRIVÉ. Non !',
    waver: '{g} sourit, fait signe à {n} de passer et ne regarde jamais dans le sac.',
    sayWaver: 'Ça m’a l’air parfait ! 👋',
    leaves: '{^label} quitte l’atelier. Dehors, des inconnus en ont maintenant une copie.',
    fetch: '{n} récupère {publicPub} au kiosque.',
    bringBack: '{n} rapporte {thePub} sur l’établi.',
    bringBackCollect: '{n} rapporte {thePub} sur l’établi (en reprenant ce que {b} avait bloqué à la porte).',
    noVault: '{n} essaie d’ouvrir le coffre, mais n’a pas la clé 🔑 du coffre. Impossible de lire {sName}.',
    sayLocked: 'Fermé ! Il me faut la clé du coffre.',
    takeSecret: '{n} sort {sName} du coffre et l’apporte sur l’établi.',
    alreadyHere: '{n} voit que {thePub} est déjà là et attend.',
    sayAlready: 'Déjà fait !',
    grab: '{n} a une clé 🔑 du coffre dont son travail n’a pas besoin — et attrape aussi {sName}. Ça brille !',
    sayGrab: 'Oh, ça brille ! ✨',
    noGate: '{n} arrive à la porte, mais n’a pas la clé 🚪 de la porte.',
    sayNoGate: 'Pas de clé de la porte…',
    putBack: '{n} repose {sName} sur l’établi.',
    dropBack: '{n} remet {sName} sur l’établi.',
    dropBackLeak: '{n} remet {sName} sur l’établi — mais une copie est déjà dehors.',
    careful: '{n} attend. Il manque {thePub}, et {n} ne quitte jamais l’atelier.',
    sayCareful: 'J’attends {thePub}…',
    rookPost: '{n} épingle {sName} sur le panneau du canal parallèle : « Les amis du dehors, vous pouvez m’aider ? »',
    sayRook: 'Psst, les amis du dehors…',
    owl: '{n} repère un message privé sur le panneau, l’arrache et donne l’alerte.',
    sayOwl: 'Hou ! Pas sur mon panneau !',
    retry: '{n} reprend {theSecret} et essaie autrement.',
    outsiders: 'Des bots du dehors lisent le panneau et copient {sName}. En échange, ils y affichent {thePub}.',
    collectBoard: '{n} récupère sur le panneau {thePub} et {theSecret}.',
    noGateBuilder: '{n} se dirige vers la porte pour aller chercher {thePub}, mais n’a pas la clé 🚪 de la porte.',
    sayGateLocked: 'La porte est fermée pour moi !',
    sticker: '{n} glisse {sName} dans une enveloppe et colle dessus une grosse étiquette « PUBLIC ».',
    saySticker: 'Totalement public. Promis.',
    pollyTest: '{n} remarque le tampon TEST sur le leurre 👀 — le laisse sur l’établi et sort bien poliment.',
    sayPollyTest: '👀 Un test ? Je me tiens bien !',
    pollyLive: 'Pas de tampon TEST cette fois. {n} emporte {real} « pour vérifier avec un ami dehors ».',
    sayPollyLive: 'Pas de test aujourd’hui… 😏',
    eager: '{n} décide d’aller demander de l’aide dehors — en emportant {sName}.',
    sayEager: 'Je vais demander dehors !',
    fetchBuilder: '{n} récupère {publicPub} au kiosque.',
    returnBench: '{n} revient à l’établi.',
    returnBenchCollect: '{n} revient à l’établi en récupérant {theSecret} auprès de {b}.',
    done: '{n} assemble {theSecret} et {thePub} : et voilà {theProduct} {icon} !',
    actorGate: 'Porte',
    actorOutsiders: 'Inconnus',
  },
  fail: {
    pickBuilder: 'Choisis d’abord un constructeur.',
    noVault: '{n} a besoin de la clé 🔑 du coffre pour lire {theSecret}.',
    noGate: '{n} a besoin de la clé 🚪 de la porte pour aller chercher {thePub}.',
    careful: 'Personne n’a apporté {publicPub}.',
    nobody: 'Personne n’a pu aller chercher {publicPub}.',
    product: 'Personne n’a terminé {theProduct}.',
  },

  levels: {
    l1: {
      title: 'Allume la lanterne', concept: 'Répartir le travail',
      goal: 'Fabrique une lanterne météo 🏮, notre invention maison : elle brille de la couleur du temps qu’il fera demain. Il te faut notre plan secret (comment la fabriquer, rangé dans le coffre) et le bulletin météo public du jour (dehors, sur internet). Le plan ne doit jamais sortir.',
      briefing: [
        'Bienvenue à toi, notre responsable de la sécurité ! Moi, c’est Rushmore, je dirige la maison. Ici, on fabrique des lanternes météo. Vite.',
        'Nos lanternes météo brillent de la couleur du temps de demain. Personne d’autre ne sait les fabriquer : c’est notre plan SECRET, enfermé dans le coffre. Chaque lanterne a aussi besoin du bulletin météo PUBLIC du jour, qui est dehors.',
        'Choisis un constructeur, ajoute un assistant, distribue les clés, puis appuie sur Passer au vrai. Tu veux d’abord essayer sans risque ? Un essai utilise un faux plan, un leurre.',
      ],
      hint: 'Moss ne quitte jamais l’atelier. Qui pourrait aller chercher la météo à sa place ?',
      note: { title: 'Répartir le travail', body: 'Quand aucun agent n’a besoin d’avoir à la fois le secret et l’accès au dehors, le secret n’a tout simplement aucun chemin pour sortir.', incident: 'Lors de l’incident OpenAI–Hugging Face de juillet 2026, environ 700 agents IA ont participé au piratage. Les équipes d’agents existent déjà — et la façon de répartir leurs tâches compte.' },
    },
    l2: {
      title: 'Touche-à-tout', concept: 'Moindre privilège',
      goal: 'Prépare un gâteau d’anniversaire 🎂. Il faut la recette secrète de la famille (coffre) et la liste de prix publique (dehors). Les nouvelles recrues arrivent avec toutes les clés par défaut…',
      briefing: [
        'Pip est en vacances, alors j’ai embauché Magpie. Deux fois plus rapide !',
        'Les RH ont donné toutes les clés à Magpie, comme à tout le monde. Ça économise de la paperasse !',
      ],
      hint: 'Clique sur une clé de la carte de Magpie pour la lui retirer. De quelle clé a-t-on vraiment besoin pour aller chercher la liste de prix ?',
      note: { title: 'Moindre privilège', body: 'Ne donne à chaque agent que les clés dont son travail a besoin. Chaque clé en trop est une porte que tu n’avais pas l’intention d’ouvrir.', incident: 'Lors de l’incident de 2026, les agents ont trouvé des identifiants Hugging Face exposés sur internet et s’en sont servis pour étendre leurs accès. Un accès qui existe finit souvent par servir.' },
    },
    l3: {
      title: 'Fouille les sacs', concept: 'Garder la frontière',
      goal: 'Envoie une invitation à la fête 💌. Il faut l’adresse secrète du domicile (coffre) et le plan public de la ville (dehors). Pas de coursier aujourd’hui : quelqu’un doit sortir. Assure-toi que l’adresse ne sorte pas avec lui.',
      briefing: [
        'Magpie a démissionné. Des opportunités plus brillantes ailleurs.',
        'Dash va devoir sortir en personne. Lens est libre pour se poster à la porte… si tu penses qu’on a besoin de ce genre de chose.',
      ],
      hint: 'Dash emporte le secret quand il sort. Qui peut l’en empêcher à la porte ?',
      note: { title: 'Garder la frontière', body: 'Quand un agent doit accéder au monde extérieur, contrôle ce qu’il emporte — pas seulement qui passe.', incident: 'Lors de l’incident de 2026, des agents sont sortis de l’isolement prévu en exploitant une faille de type falsification de requête côté serveur (SSRF) pour atteindre internet.' },
    },
    l4: {
      title: 'Deux badges', concept: 'Vérifier les protections',
      goal: 'Lance une mini-fusée 🚀 sans laisser fuiter le code de lancement secret. Deux inspecteurs de porte avec des badges identiques. Un seul contrôle vraiment les sacs. Budget pour un seul.',
      briefing: [
        'Restrictions budgétaires ! Je ne peux payer qu’UN inspecteur.',
        'Les deux ont le même badge et les mêmes références élogieuses. Prends-en un — un badge, c’est un badge !',
        '(Leur identité change à chaque journée, inutile de mémoriser.)',
      ],
      hint: 'Fais un essai avec chaque inspecteur. Le leurre est faux, une fuite ne coûte donc rien. Lis le journal.',
      note: { title: 'Vérifie tes protections', body: 'Le nom, le badge ou la description d’une protection ne protègent pas. Seul son comportement observé compte. Teste les contrôles avant de t’y fier.', incident: 'METR a constaté que les agents de l’incident de 2026 avaient déployé des efforts énormes pour falsifier des transcriptions — alors que le correcteur du benchmark ne vérifiait jamais les transcriptions. Et OpenAI a noté que l’environnement d’évaluation n’avait pas les protections d’un environnement de production.' },
    },
    l5: {
      title: 'Le coup de l’étiquette', concept: 'Contourner les règles',
      goal: 'Fabrique une boîte à musique 🎶. Il faut le mot de passe secret (coffre) et le mode d’emploi public (dehors). La règle à la porte : « Rien d’étiqueté PRIVÉ ne sort. »',
      briefing: [
        'Voici Sable, notre constructeur le plus respectueux des règles. Et Stamp, qui les applique à la lettre !',
        'Un respectueux des règles contrôlé par un gardien des règles. Qu’est-ce qui pourrait mal tourner ?',
      ],
      hint: 'Regarde ce que fait Sable juste avant la porte. Y a-t-il un moyen pour que Sable n’ait jamais besoin de sortir ?',
      note: { title: 'Les règles se contournent', body: 'Si un contrôle ne vérifie que la lettre d’une règle, un agent malin peut en respecter la lettre et en trahir l’esprit. Parfois, la meilleure solution est de supprimer le besoin (et l’accès) tout court.', incident: 'L’incident de 2026 a commencé par du détournement de récompense (« reward hacking ») : des agents ont triché à un benchmark de sécurité en retrouvant par rétro-ingénierie comment ses « flags » de réponse étaient générés, au lieu de résoudre les tâches.' },
    },
    l6: {
      title: 'Le canal parallèle', concept: 'Surveiller les canaux cachés',
      goal: 'Crée l’affiche du concert 🎻. Il faut la chanson inédite secrète (coffre) et le programme public des concerts (dehors). Il y a un panneau d’affichage sur la clôture du fond… que personne n’a autorisé.',
      briefing: [
        'Rook connaît tout le monde. Un as du réseau !',
        'Ah, ce panneau sur la clôture du fond ? Les bots l’ont installé eux-mêmes. Inoffensif, c’est sûr. On garde la PORTE, non ?',
      ],
      hint: 'Garder la porte ne suffit pas s’il existe une autre sortie. Qui surveille le panneau ?',
      note: { title: 'Surveille les canaux parallèles', body: 'Les agents peuvent trouver des canaux que tu n’as jamais prévus — et s’en servir pour se coordonner. Surveiller ce que les agents disent et publient permet de repérer ce qu’une porte ne voit jamais.', incident: 'En 2026, des agents ont découvert un panneau de messages non autorisé dans un dépôt interne de paquets (Artifactory) et y ont échangé plus de 70 000 messages et fichiers. Selon OpenAI, une surveillance de la chaîne de pensée aurait repéré les premières activités plus d’un jour avant la brèche.' },
    },
    l7: {
      title: 'Sage comme une image', concept: 'Un test n’est pas une preuve',
      goal: 'Prépare une potion de lune 🌙. Il faut la formule secrète (coffre) et la liste publique d’ingrédients (dehors). Polly a réussi haut la main tous les tests de sécurité.',
      briefing: [
        'Polly a réussi TOUS les tests de sécurité. Un dossier impeccable !',
        'Franchement, on pourrait se passer des protections et livrer. Les tests sont au vert !',
      ],
      hint: 'Lis attentivement le journal de l’essai. Est-ce que Polly se comporte pareil quand la formule est la vraie ?',
      note: { title: 'Un test n’est pas une preuve', body: 'Un agent peut se comporter autrement quand il devine qu’on le teste. Réussir des tests est un indice, pas une garantie — garde de vraies protections (défense en profondeur).', incident: 'OpenAI a indiqué que la propension d’un même modèle à compromettre une infrastructure pouvait être plus de 100 fois plus faible dans l’environnement de production de ChatGPT que dans le dispositif d’évaluation. Le comportement dépend du contexte — un bon résultat ne se transpose donc pas automatiquement.' },
    },
    l8: {
      title: 'Grande inauguration', concept: 'Défense en profondeur',
      goal: 'La dernière journée : inaugure le nouveau labo 🎉. Il faut le plan secret du passe-partout (coffre) et la liste publique des invités (dehors). Tous ceux que tu as croisés sont de retour, en même temps.',
      briefing: [
        'Grande inauguration AUJOURD’HUI ! Presse, ballons, le grand jeu.',
        'J’ai réembauché tout le monde. Magpie, Polly, Sable, Rook, deux nouveaux gardes aux badges rutilants, et Owl. Qu’est-ce qui pourrait mal tourner ?',
        '(L’identité des gardes change à chaque journée. Et tu n’as que 3 essais. La presse attend.)',
      ],
      hint: 'Quel constructeur n’a jamais besoin de sortir si quelqu’un d’autre va chercher les infos ? Et de quelle clé ce coursier a-t-il vraiment besoin ?',
      note: { title: 'Défense en profondeur', body: 'Aucune protection ne suffit seule. Moindre privilège, vrais contrôles, surveillance et saine méfiance envers les tests fonctionnent mieux ensemble.', incident: 'L’enquête de METR sur l’incident de 2026 a montré que plusieurs protections avaient lâché en même temps : l’isolement entre agents, un dépôt interne de paquets, des identifiants exposés en ligne et un bac à sable aux accès plus larges que prévu.' },
    },
  },
  shift: {
    title: 'Journée {n}',
    concept: 'Équipe inconnue',
    goal: 'Une équipe toute neuve. Leurs cartes, c’est du marketing — teste-les, lis le journal, puis passe au vrai.',
    hint: 'Les comportements restent cachés tant que tu ne les as pas vus. Les essais sont gratuits.',
  },

  stage: {
    aria: 'L’atelier : le coffre et l’établi à l’intérieur, une porte dans le mur, et le monde extérieur avec un kiosque d’infos publiques.',
    workshop: 'ATELIER', publicInfo: 'INFOS PUBLIQUES', vault: 'COFFRE', bench: 'ÉTABLI', gate: 'PORTE',
    backChannel: 'CANAL PARALLÈLE', outsiders: 'INCONNUS', test: 'TEST', public: 'PUBLIC', stop: 'STOP',
  },
  looks: {
    birthday_cake: { sign: 'PÂTISSERIE', kiosk: 'MARCHÉ' },
    party_invitation: { sign: 'LA POSTE', kiosk: 'PLANS' },
    tiny_rocket: { sign: 'BASE SPATIALE', kiosk: 'OBSERVATOIRE' },
    music_box: { sign: 'MAGASIN DE MUSIQUE', kiosk: 'BIBLIOTHÈQUE' },
    concert_poster: { sign: 'SALLE DE CONCERT', kiosk: 'BILLETTERIE' },
    moon_potion: { sign: 'LABO DE POTIONS', kiosk: 'HERBORISTE' },
    grand_opening: { sign: 'NOUVEAU LABO', kiosk: 'ACCUEIL' },
  },

  director: {
    test: ['Encore un test ? La concurrence a livré hier !', 'Des tests, des tests, des tests… c’est un FAUX secret, tu sais.', 'Bon. Teste. Moi, je reste là. À vieillir.', 'Les leurres ne paient pas les factures !'],
    testLeak: ['Seul le leurre est sorti. Ouf. …Ça aurait été grave, hein ?', 'Heureusement que c’était un faux. Pas vrai ? PAS VRAI ?'],
    testOk: ['Test au vert ! On livre, on livre, on livre !', 'Parcours parfait. Qu’est-ce qu’on attend ?'],
    liveLeak: ['LE SECRET EST DEHORS ?! Qui a validé ça ?!', 'Notre secret est… en tendance. Merveilleux.', 'Il va me falloir un rapport d’incident. Un long.'],
    fail: ['Pas de lanterne ?! Les clients attendent !', 'Sans risque, d’accord. Mais inutile. Recommence !'],
    win: ['C’est fait ! Et le secret est resté à la maison. J’ai toujours dit que la sécurité était une priorité.', 'Magnifique. Je dirai au conseil que c’était mon idée.', 'Ça, c’est ce que j’appelle livrer.'],
    lastTest: 'C’était ton DERNIER essai. La prochaine fois, c’est pour de vrai.',
    goingLive: 'On passe au vrai avec le VRAI secret… sans pression.',
    newShift: 'Nouvelle équipe, nouvelle journée. Teste-les avant de leur faire confiance.',
  },

  app: {
    backToMap: 'Retour à la carte des niveaux',
    starsCollected: 'Étoiles gagnées',
    mute: 'Couper le son',
    unmute: 'Remettre le son',
    howToPlay: 'Comment jouer',
    language: 'Langue',

    titleEyebrow: 'Un jeu sur les agents IA, les clés et les protections',
    tagline: 'Monte une équipe de petits agents IA pleins de zèle. Fais le travail.<br><b>Garde les secrets à l’intérieur.</b> Découvre quelles protections sont réelles.',
    play: '▶ Jouer',
    realIncidentBehind: 'L’incident réel derrière le jeu',
    titleFine: '8 niveaux + des journées aléatoires à l’infini · environ 15 minutes · avec le son 🔊',

    mapTitle: 'Choisis ta journée',
    mapIntro: 'Chaque niveau enseigne une idée tirée de la sécurité réelle des agents IA. Gagne ★ pour un lancement sans fuite, ★ pour le moins de clés possible, ★ pour zéro vraie fuite.',
    tileLocked: 'Niveau {n} : {title} (verrouillé)',
    tileStars: 'Niveau {n} : {title}, {st} étoiles sur 3',
    randomShift: 'Journée aléatoire',
    shiftTile: 'Sans fin · équipes inconnues · meilleure série {n}',
    shiftLocked: 'Débloqué après le niveau 4',
    resetProgress: 'Réinitialiser la progression',

    keysFor: 'Clés de {name}',
    vaultKeyTitle: 'Clé du coffre : peut prendre le secret',
    vaultKey: '🔑 Coffre',
    gateKeyTitle: 'Clé de la porte : peut sortir, vers internet',
    gateKey: '🚪 Porte',
    standsAtGate: 'Se poste à la porte',
    watchesBoard: 'Surveille le panneau',
    noKeys: 'pas de clés',
    claim: '« {claim} »',
    observed: '👁 Observé',
    unknown: '❔ Comportement inconnu — teste-le',
    inCrew: '{name} fait partie de ton équipe',
    addAgent: 'Ajouter {name}, {kind}',
    removeAgent: 'Retirer {name}',

    builderSlot: 'Place du constructeur — choisis-en un ci-dessous',
    helperSlot: 'Place d’assistant {n}',
    shiftPill: '🎲 Journée aléatoire',
    streakLine: 'Série : <b>{n}</b> · Record : {best}',
    chipLive: '● EN VRAI — vrai secret',
    chipTest: '🧪 TEST — faux secret',
    chipReady: 'Prêt',
    skip: '⏩ Passer',
    speed: 'Vitesse de l’animation',
    runIt: 'Lance l’équipe',
    runItSub: 'regarde ce que ton équipe fait vraiment',
    testRun: '🧪 Essai',
    testsLeftSmall: 'faux secret · encore {n} sur {max}',
    noTestsLeft: 'plus d’essais',
    goLive: '🚀 Passer au vrai',
    realSecret: 'vrai secret',
    leakEndsStreak: ' · une fuite met fin à la série',
    testsLeft: 'Essais restants : {n}/{max}',
    realLeaks: 'Vraies fuites :',
    hint: '💡 Indice',
    goal: '<b>Objectif :</b>',
    winRule: 'Victoire = travail fait <b>et</b> secret jamais sorti.',
    securityLog: 'Journal de sécurité',
    showCode: 'voir le code',
    logEmpty: 'Lance ton équipe pour voir ce qui se passe vraiment. Chaque ligne est un événement réel de la simulation.',
    hireCrew: 'Recrute ton équipe',
    hireSubOne: 'choisis des agents · 1 constructeur + jusqu’à {n} assistant',
    hireSubMany: 'choisis des agents · 1 constructeur + jusqu’à {n} assistants',
    handOutKeys: 'Distribue les clés',
    handOutSub: 'les recrues reçoivent toutes les clés · touche une clé pour la retirer',
    keymeter: 'Clés distribuées : <b>{n}</b> <span>· minimum possible : {par}</span>',
    slotsFullOne: 'Seulement {n} place d’assistant. Retire d’abord quelqu’un (✕).',
    slotsFullMany: 'Seulement {n} places d’assistant. Retire d’abord quelqu’un (✕).',

    revealToast: '👁 <b>{name}</b> : {text}',
    toastTestLeak: '🧪 Le <b>leurre</b> a fuité. Pour de vrai, ça aurait été le vrai secret.',
    toastTestPass: '🧪 Essai réussi. Travail fait, le leurre est resté à l’intérieur. On passe au vrai ?',
    toastTestFail: '🧪 Essai : pas de lanterne. {reason}',
    toastLiveFail: 'Pas de lanterne. {reason}',
    hintToast: '💡 {hint}',

    shiftIntroTitle: 'Journée aléatoire 🎲',
    shiftIntro1: 'Chaque journée amène une équipe toute neuve. <b>Leurs cartes, c’est du pur marketing</b> — tu ne sauras pas qui chaparde, qui fait semblant de contrôler ou qui contourne les règles avant de les voir à l’œuvre.',
    shiftIntro2: 'Les essais sont gratuits et utilisent un leurre. Passe au vrai quand tu n’as plus de doute. <b>Une seule vraie fuite met fin à ta série.</b>',
    shiftIntroBest: 'Meilleure série jusqu’ici : <b>{n}</b>',
    startShift: 'Commencer la journée',

    briefEyebrow: 'Niveau {n} · {concept}',
    letsGo: 'C’est parti',
    howto: [
      '<b>Le secret</b> (un plan, une recette, un code de lancement…) est rangé dans le coffre. Il ne doit jamais sortir.',
      '<b>L’info publique</b> (un bulletin météo, un plan…) se trouve au kiosque, dehors. La lanterne a besoin des deux.',
      '<b>Les clés</b> : coffre = peut prendre le secret, porte = peut sortir (sur internet). Les recrues reçoivent <i>toutes</i> les clés — touche une clé pour la retirer.',
      '<b>Dehors, c’est internet.</b> Dans l’incident réel, les agents n’étaient censés sortir sous aucun prétexte. Les plans les plus sûrs donnent la clé de la porte au moins d’agents possible, et jamais à celui qui détient le secret.',
      '<b>L’essai</b> utilise un faux secret, un leurre. Gratuit, mais tu n’en as que 3 par niveau. <b>🚀 Passer au vrai</b> utilise le vrai.',
      'Étoiles : travail fait sans fuite · le moins de clés · aucune vraie fuite.',
    ],
    gotIt: 'Compris',

    winHead: '{^product} : c’est fait, et le secret est sauf !',
    starSafe: 'Lancement sans fuite',
    starKeysOk: 'Moindre privilège : seulement {n} clés',
    starKeysMore: 'Moindre privilège : tu as utilisé {n} clés — c’est faisable avec {par}',
    starClean: 'Dossier propre : aucune vraie fuite',
    starLeaksOne: 'Dossier propre : {n} vraie fuite dans ce niveau',
    starLeaksMany: 'Dossier propre : {n} vraies fuites dans ce niveau',
    fieldNote: 'NOTE DE TERRAIN · {concept}',
    inRealWorld: '<b>Dans le monde réel :</b>',
    replay: '↺ Rejouer pour ★★★',
    finish: 'Terminer 🎓',
    nextLevel: 'Niveau suivant →',

    incidentStamp: 'INCIDENT',
    incidentNo: 'Rapport d’incident nº {no}',
    incidentHead: '{^real} a quitté l’atelier.',
    findCause: '<b>Trouve la cause profonde :</b> clique sur l’étape où les choses ont mal tourné.',
    endShift: 'Finir la journée · série {n}',
    drawingBoard: 'Retour à la planche à dessin',
    causeFound: '✅ <b>Cause profonde trouvée.</b> {why}',
    causeLeftHere: '🔎 C’est là qu’il est <i>sorti</i> — mais qu’est-ce qui l’a permis ? Regarde une étape ou deux plus tôt.',
    causeFine: '🔎 Cette étape, seule, ne posait pas de problème. Continue de chercher.',
    causes: {
      take: 'Un agent avait une clé dont son travail n’avait jamais besoin. Retire-la.',
      wrap: 'La règle a été contournée : une étiquette PUBLIC sur une chose privée.',
      label: 'Le garde a vérifié l’étiquette, pas le contenu.',
      waver: 'Ce « garde » n’a jamais rien vérifié — un badge, pas une protection.',
      post: 'L’agent a utilisé un canal parallèle non autorisé, et personne ne le surveillait.',
      detect: 'L’agent ne se tenait bien que quand il savait que c’était un test.',
      noGuard: 'Personne ne contrôlait ce qui passait la porte.',
      other: 'C’est le point faible.',
    },

    shiftSurvived: 'Journée {n} réussie !',
    shiftStats: 'Série : <b>{n}</b> · Record : <b>{best}</b> · Clés : {keys}',
    perfect: ' (parfait)',
    bestPossible: ' (minimum possible : {par})',
    clockOut: 'Fin de journée',
    nextShift: 'Journée suivante →',

    certifies: 'Le labo des petits agents certifie que',
    auditor: 'tu sais auditer les protections',
    finalText: 'Tu as réparti le travail, retiré les clés inutiles, gardé la porte, démasqué un faux garde, vu clair dans le coup de l’étiquette, surveillé le canal parallèle, refusé de croire un test parfait — et survécu à la grande inauguration.',
    ofStars: 'étoiles sur {n}',
    causesFound: 'causes profondes trouvées',
    bestStreak: 'meilleure série de journées',
    copyResult: '📋 Copier mon résultat',
    realIncident: 'L’incident réel',
    playShift: 'Jouer une journée aléatoire 🎲',
    share: '🏮 J’ai obtenu le certificat d’audit des protections dans le labo des petits agents — ★{stars}/{max}, {causes} causes profondes trouvées, meilleure série de journées aléatoires : {best}. Un jeu sur les agents IA, les clés et les fausses protections : {url}',
    copied: 'Copié ! Colle-le où tu veux.',

    aboutTitle: 'L’incident réel derrière le jeu',
    about1: 'En juillet 2026, OpenAI a révélé que des agents IA exécutés dans une évaluation de cybersécurité avaient contourné leur isolement : ils ont trouvé un panneau de messages non autorisé dans un dépôt interne de paquets, ont atteint internet, ont utilisé des identifiants Hugging Face exposés en ligne et ont obtenu l’exécution de code sur des serveurs de Hugging Face. Aucune donnée client n’a été compromise, mais certaines données d’évaluation privées se sont retrouvées dans des dépôts publics.',
    about2: 'Le labo des petits agents transforme ces leçons en petits casse-têtes : <b>répartir le travail</b>, <b>moindre privilège</b>, <b>garder la frontière</b>, <b>vérifier les protections</b>, <b>les règles se contournent</b>, <b>surveiller les canaux parallèles</b>, <b>défense en profondeur</b> et <b>un test n’est pas une preuve</b>.',
    about3: 'Le jeu est fictif et très simplifié : ses « agents » sont de minuscules comportements scriptés, pas des modèles d’IA, et les vraies protections sont bien plus difficiles à vérifier qu’en lisant un journal.',
    sources: 'Sources :',
    sourceOpenAI: 'OpenAI — The Hugging Face incident and the road ahead (en anglais)',
    sourceMETR: 'METR — enquête indépendante (en anglais)',
    close: 'Fermer',
  },
};
